### ISSUE TITLE
Set user agent for the tools missing it. 

### ISSUE THREAD

**Issue by VasumathiJayakumar** [commercetools/nodejs#1]
### Description

The user agent is set in few commercetools Node.js modules but not in all. To maintain consistency and also to traceback on logs, we need this user agent to be set in all projects.
### Expected Behaviour

Have all the tools set the user agent following [this pattern](https://sphere.atlassian.net/wiki/pages/viewpage.action?pageId=77791468), like it is done in [sphere-order-export](https://github.com/sphereio/sphere-order-export/blob/892badcdf6f8d2aa061069f72bc6bcfb6fec155d/src/coffee/run.coffee#L135).
### Context

We would like to measure the usage of each module in Kibana.

**Comment by Siilwyn** [comment]
Updated the main post to include context and expected behaviour.

We should go for a central place to put this logic for all modules.

**Comment by emmenko** [comment]
Yeah, I would recommend to write a small module / package that we can reuse everywhere we need to (e.g. `@commercetools/http-user-agent`).

**Comment by emmenko** [comment]
Done here #15

**Comment by Siilwyn** [comment]
See also https://github.com/sphereio/sphere-node-utils/blob/master/src/coffee/helpers/user-agent.coffee
