### ISSUE TITLE
[api-request-builder] Add markMatchingVariants

### ISSUE THREAD

**Issue by hisabimbola** [commercetools/nodejs#100]
### Description

A duplicate of this [issue](https://github.com/sphereio/sphere-node-sdk/issues/207)
Instead of implementing it there, it will be implemented here.
Fixes sphereio/sphere-node-sdk#207

**Comment by junajan** [comment]
Hello @hisabimbola .. Is this issue needed? In the current `master` branch there is already a function for adding a `markMatchingVariants` parameter to the query string.

Function is here:
https://github.com/commercetools/nodejs/blob/master/packages/api-request-builder/src/query-search.js

And here:
https://github.com/commercetools/nodejs/blob/master/packages/api-request-builder/src/build-query-string.js#L60

Also, there is a test here:
https://github.com/commercetools/nodejs/blob/master/packages/api-request-builder/test/build-query-string.spec.js#L68

**Comment by wizzy25** [comment]
@junajan The issue is for the old sdk... Except we wouldn't be adding new features to it

**Comment by hisabimbola** [comment]
Yeah, this issue is not valid.

Thanks for pointing out @junajan
