### ISSUE TITLE
[sdk-auth] Invalidate token to use new flow

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/nodejs#1006]
### Description

I'm using the sdk-auth module with the TokenProvider and I have initialized it with the following:
```
const tokenProvider = new TokenProvider({
  sdkAuth: new SdkAuth({ ... }),
  fetchTokenInfo: sdkAuth => sdkAuth.clientCredentialsFlow(),
  ...
});
```
When a customer logs in, I want to change the way the token is fetched with:
```
  tokenProvider.fetchTokenInfo = sdkAuth => sdkAuth.customerPasswordFlow({ username, password });
```
But when I do this, the tokenProvider still returns me the old token instead of giving me a new token with the new flow.

### Expected Behavior

When I change the fetchTokenInfo function because of logging in, I would like the new token provided (by calling `tokenProvider.getTokenInfo()`) to be fetched with the new flow.

### Current Behavior

When I call `tokenProvider.getTokenInfo()`, it still gives me the token from the old flow.

### Context

I'm trying to use the sdk-auth to authenticate to commercetools using Apollo as the GraphQL client.

### Possible Solution

Providing a method to invalidate the token, so that I ensure that the next call of `tokenProvider.getTokenInfo()` will invoke the new flow.

**Comment by lauraluiz** [comment]
@skyriakou @junajan please check

**Comment by skyriakou** [comment]
@junajan ticket is now on the ready column in the board

**Comment by junajan** [comment]
thanks.. will start working on it soon

**Comment by junajan** [comment]
Hi @lauraluiz .. what do you think about invalidating `tokenInfo` by some special method instead of checking when the new `fetchTokenInfo` was set?

**Comment by junajan** [comment]
cool... will do it that way. For now, you can change `fetchTokenInfo()` method and then set `tokenInfo` to `null` which should trigger `fetchTokenInfo()` method next time you call `getTokenInfo()`

**Comment by lauraluiz** [comment]
I’m detecting some issues with the TokenProvider:

1st) I think it’s not taking into account that there might be a request on flight to fetch the token, because I’m seeing multiple requests of token on parallel.

2nd) inside `onTokenInfoChanged` the `refresh_token` seems to always be undefined, even though I can see the token info in the response contains it.
