### ISSUE TITLE
add support for HEAD methods on `sdk-middleware-http`

### ISSUE THREAD

**Issue by adnasa** [commercetools/nodejs#1022]
### Support reference number

- [PCM-1078](https://jira.commercetools.com/browse/PCM-1078)

### Description

On `sdk-middleware-http`, there is a lack of support for clients to send `HEAD` requests.

The request is sent, however the promise from the request couldn't resolve, since the fetcher itself expects that there is a body to be parsed

https://github.com/commercetools/nodejs/blob/4d5391c295c7a1b83ddf94564a8a45b3290a16ca/packages/sdk-middleware-http/src/http.js#L112

However a HEAD response doesn't contain any body

### Expected Behavior

Resolve the promise of the request even when the method is `HEAD`

### Current Behavior

At the moment, the request is sent to the API.
When the API responds, the promise for a request couldn't be resolved.

### Context

We want to use HEAD request in a use case such as checking if a server is up and running or an index of a specific project is still active

### Possible Solution

Update `http.js` to call `next` and return

**Comment by adnasa** [comment]
cc @pa3 for awareness

**Comment by dferber90** [comment]
I ran into this same issue as well in https://github.com/commercetools/merchant-center-application-kit/pull/209#discussion_r242233605.

My use-case is the same as @adnasa. A workaround for that specific case seems to be to just do a regular `POST` request and read the response. It would be nice if we could use a `HEAD` request and if the middleware supported it though.
