### ISSUE TITLE
[api-request-builder] Support version when deleting

### ISSUE THREAD

**Issue by hisabimbola** [commercetools/nodejs#112]
### Description

Currently to do a delete, you have to manually add the version to the uri.

I find the user experience of this very bad, especially when compared to the old SDK

### Expected Behavior

Should expose a method like service.delete(versionNumber).build()
### Current Behavior

Example of current behaviour can be found [here](https://github.com/commercetools/nodejs/blob/6dce24c25665289ae7d21329a6f1b026b5a7096f/integration-tests/sdk/channels.it.js#L141)

**Comment by wizzy25** [comment]
I smell breaking change @hisabimbola
