### ISSUE TITLE
How to manage multiple guest checkouts?

### ISSUE THREAD

**Issue by StarpTech** [commercetools/nodejs#1196]
Hi,
according to the docs https://docs.commercetools.com/tutorial-anonymous-session I can simply create a client with:

```js
  const authMiddleware = createAuthMiddlewareForAnonymousSessionFlow({
    host: clientOpts.authUrl,
    projectKey: clientOpts.projectKey,
    credentials: {
      clientId: clientOpts.clientId,
      clientSecret: clientOpts.secret
    },
    scopes: [clientOpts.scope],
    fetch: clientOpts.fetch
  });

  const httpMiddleware = createHttpMiddleware({
    host: clientOpts.apiUrl,
    fetch: clientOpts.fetch
  });

  return createClient({
    middlewares: [authMiddleware, httpMiddleware]
  });
```
and the client will handle the complete OAuth flow for me. Refer to the [code](https://github.com/commercetools/nodejs/blob/master/packages/sdk-middleware-auth/src/base-auth-flow.js#L162) it should also handle the refresh of the token right?

My other question is how can I access the refresh token from the client in order restore the session when my application goes down? __or__ how can I manage N guests do I need to maintain a client pool?

I'm looking for a way to easily continue the session of my guests

**Comment by StarpTech** [comment]
I got it. I have to instantiate the `SdkAuth`, `TokenProvider` by myself and use the `createAuthMiddlewareWithExistingToken` to operate in the correct context with the client. :+1:

**Comment by aholland909** [comment]
@StarpTech Are you able to give some examples on how you managed this with SdkAuth and createAuthMiddlewareWithExistingToken?
