### ISSUE TITLE
Can't create Order from anonymous cart

### ISSUE THREAD

**Issue by StarpTech** [commercetools/nodejs#1216]
Hello, I can't create an Order from an anonymous cart. I got the error:

```
ERROR [1553277027860] (BadRequest/6749 on tefr): Shipping address is not set.
    BadRequest: Shipping address is not set.
        at createError (/home/deus/Repositories/tzt/node_modules/@commercetools/sdk-middleware-http/dist/commercetools-sdk-middleware-http.cjs.js:235:29)
        at /home/deus/Repositories/tzt/node_modules/@commercetools/sdk-middleware-http/dist/commercetools-sdk-middleware-http.cjs.js:341:25
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```

Before we are trying to create an order we also set a new shipping address, even when it's optional according to the docs. The request was successfully and a new cart version was returned.

```js

    const cart = await this.client.execute({
        uri: `/${PROJECT_KEY}/me/active-cart`,
        method: 'GET'
      });
    const result = await this.client.execute({
      uri: `/${PROJECT_KEY}/me/carts/${id}`,
      method: 'POST',
      body: {
        version,
        actions: [
          {
            action: 'setShippingAddress',
            country: 'DE'
          }
        ]
      }
    });

  const result = await this.client.execute({
      uri: `/${PROJECT_KEY}/me/orders`,
      method: 'POST',
      body: {
        id,
        version
      }
    });
```
Even after setting the shipping address the same response is returned. We double check the accesstoken and anonymousSessionId they are the same.

This looks like a bug to me. Any ideas?

**Comment by StarpTech** [comment]
The workaround is to set the `shippingAddress` at cart creation. After this, now we run into the issue `BadRequest: Permissions exceeded` our client has full access `manage_project`.

**Comment by daern91** [comment]
Hi @StarpTech, this sounds more like a platform issue than an issue with the Node SDK. Could you please enter a ticket for our support team instead?
https://jira.commercetools.com/servicedesk/customer/portal/1
