### ISSUE TITLE
Can't create api client with scope "manage_my_profile"

### ISSUE THREAD

**Issue by StarpTech** [commercetools/nodejs#1217]
As titled. In the Admin dashboard there is no scope "Manage my Profile".
How can we enable it? This feature is required for us because we want to create a user from an anonymous session.

**Comment by StarpTech** [comment]
We could found the checkbox to enable it but even with the scope `manage_project` we can't operate with `my profile` ressources. We got the error `BadRequest: Permissions exceeded`.

**Comment by daern91** [comment]
Hi @StarpTech, this sounds more like a platform issue than an issue with the Node SDK. Could you please enter a ticket for our support team instead?
https://jira.commercetools.com/servicedesk/customer/portal/1
