### ISSUE TITLE
Is grouping supported?

### ISSUE THREAD

**Issue by StarpTech** [commercetools/nodejs#1227]
Hello, is it possible to "group" all effected categories from a production search result?

**Comment by daern91** [comment]
Hi again @StarpTech, thanks for the question. Could you please try to elaborate a bit on what you mean here? With our [GraphQL API](https://docs.commercetools.com/graphql-api#graphql-api) you could definitely return exactly what you need but maybe this is not what you are looking for?

**Comment by StarpTech** [comment]
Hi @daern91 imagine following scenario:

You have a product-list page and want to provide a filter for categorys which definitly effect the search result so I want to get the categories incl. sub-catgeories of my search result. I think "grouping" is what I'm loking for.

**Comment by daern91** [comment]
You mean expanding any `parent` or `ancestors` references? If so, that's definitely supported, please have look at `queryExpand` here: https://commercetools.github.io/nodejs/sdk/api/apiRequestBuilder.html#arguments

Also, there are more details on it in the API docs here: https://docs.commercetools.com/http-api.html#reference-expansion

Does that solve it? Please let me know if I misunderstood your question.

**Comment by StarpTech** [comment]
@daern91 I'm aware of that functionality but it doesn't solve my issue.
I don't want to iterate through all products and group or sort the categories on my own.

**Comment by daern91** [comment]
Got it. Then I'm afraid this is currently not supported. It should be possible to add it to the roadmap though if you file a request to support.
