### ISSUE TITLE
[Sync-actions] Customer ResourceIdentifier by Key

### ISSUE THREAD

**Issue by chrisandrews7** [commercetools/nodejs#1229]
### Description

In the HTTP API it is possible to set the customerGroup property on a [customer](https://docs.commercetools.com/http-api-projects-customers) by using a [key](https://docs.commercetools.com/http-api-types.html#resourceidentifier-by-key) as the reference. However when using [Sync-actions](https://commercetools.github.io/nodejs/sdk/api/syncActions.html) to do the same, the key value is omitted.

### Expected Behavior
```js
const before = {}
const now = {
  customerGroup: {
    typeId: "customer-group",
    key: "Test",
  },
}
const actual = customerSync.buildActions(now, before)
```
I expected the following output:
```
{
  "actions": [{
    "action": "setCustomerGroup",
    "customerGroup": {
      "typeId": "customer-group"
      "key": "Test"
    }
  }]
}
```

### Current Behavior

In the HTTP API it is possible to set the customerGroup property on a [customer](https://docs.commercetools.com/http-api-projects-customers) by using a [key](https://docs.commercetools.com/http-api-types.html#resourceidentifier-by-key) as the reference:
```
-- POST {{BASE_URL}}/customers/{{id}}
{
  "actions": [{
    "action": "setCustomerGroup",
    "customerGroup": {
      "key": "Test",
      "typeId": "customer-group"
    }
  }]
}
```
However when trying to do the same using sync-actions, key is omitted
```js
const before = {}
const now = {
  customerGroup: {
    typeId: "customer-group",
    key: "Test",
  },
}
const actual = customerSync.buildActions(now, before)
```
This will output:
```
{
  "actions": [{
    "action": "setCustomerGroup",
    "customerGroup": {
      "typeId": "customer-group"
    }
  }]
}
```

**Comment by skyriakou** [comment]
@chrisandrews7 Thanks for reaching out. We will look into it. Thanks:)
