### ISSUE TITLE
[Sync-actions] ProductTypes changeAttributeOrderByName

### ISSUE THREAD

**Issue by jluterek** [commercetools/nodejs#1252]
### Description

In the HTTP API it is possible to update the order of attributes on ProductTypes through the _changeAttributeOrderByName_ update action.  This order is important for customers using the Merchant Center.

Currently the Sync-Actions library does not support this update.

### Expected Behavior

```js
before = {
  id: "00000000-0000-0000-0000-000000000001",
  attributes: [
    {
      name: "color"
    },
    {
      name: "material"
    }
  ]
}
now = {
  id: "00000000-0000-0000-0000-000000000001",
  "attributes": [
    {
      name: "material"
    },
    {
      name: "color"
    }
  ]
}
updateActions = productTypesSync.buildActions(now, before)

expect(updateActions).toEqual([
  {
    action: 'changeAttributeOrderByName',
    attributeNames : ['material', 'color'],
  },
])
```

### Current Behavior

No update actions are provided.

### Context

This is a direct request from a client.  They are storing ProductType configuration within source control and have deployment scripts for changes.  They are leveraging the Sync-Actions library for determining updates and have asked if we could implement this feature.

**Comment by skyriakou** [comment]
@junajan can you have a look at this? Thanks.

**Comment by junajan** [comment]
Hello guys.. PR opened here https://github.com/commercetools/nodejs/pull/1269
