### ISSUE TITLE
How to write tests? Does exist a development sandbox?

### ISSUE THREAD

**Issue by StarpTech** [commercetools/nodejs#1254]
I saw https://commercetools.github.io/nodejs/sdk/Testing.html but it only shows the `mocking` approach. I would like to write integrations tests to ensure that commercetools really works and to simplify my tests.

Mocking requires a lot effort to understand all different request values from commercetools in my testing setup.

The ideal setup would be:

- Create a development sandbox based on the last state of the project where all writes can be discarded after testing.

**Comment by daern91** [comment]
Hi @StarpTech, 

Did you check out any of these integration tests? 
https://github.com/commercetools/nodejs/tree/master/integration-tests/cli

I think they could give you some good inspiration on how we've written some of ours using `jest`. They are also using [these](https://github.com/commercetools/nodejs/blob/master/integration-tests/cli/helpers/utils.js) handy util functions for [creating](https://github.com/commercetools/nodejs/blob/ac16d688327ebb2c62360fd4e436e2fbe7cd71d5/integration-tests/cli/helpers/utils.js#L46-L66) and [clearing](https://github.com/commercetools/nodejs/blob/ac16d688327ebb2c62360fd4e436e2fbe7cd71d5/integration-tests/cli/helpers/utils.js#L7-L44) test data.

**Comment by StarpTech** [comment]
Hi @daern91 thank you. This helps a lot but how can I create a sandbox env based on an existing project? Please don't tell me that I need to persist everything as code ?!

**Comment by daern91** [comment]
It is possible to clone a project to set that up. Please reach out to support and they should be able to do it for you.

**Comment by emmenko** [comment]
> Create a development sandbox based on the last state of the project where all writes can be discarded after testing

That is currently not possible in our platform, you would need to clean things manually. I also wouldn't recommend using your "production" project as a test target.

> Mocking requires a lot effort to understand all different request values from commercetools in my testing setup.

Well yeah, sort of. It depends on the API that you need to mock. Some are simple, some are a bit more complex.

Can you maybe explain a bit more what sorts of things are you planning to test? E.g. creating orders, searching for products, etc.

**Comment by StarpTech** [comment]
I will try to explain a bit more from customer perspective.
When I use a headless ecommerce solution like commercetools I expect that writing tests in any way is a no brainer because the tooling is exceptional. During rapid-prototyping we didn't focused on integrations tests but rather on end-to-end tests. Now, we want to cover them as well and I need asssistent in following sections:

1. Setup a project in code
2. Create the same data (incl relations, same ID's) as in the project without to cast the whole project in code.
3.  Regular usage of the HTTP API e.g create an anonymous session and add something to the cart.
4. Delete a project in code

My point is here is that I'm looking for the functionality to run a test suite against a fixed project rather to replicate it as code. In other words project snapshotting :smile:

I see that there is no support for it and the regular way is to create a project in the admin center and to create/clean-up everything server-side. Thank you.

**Comment by emmenko** [comment]
Yeah, thanks for the feedback. I see your point and it would obviously be nice to have.

> I see that there is no support for it and the regular way is to create a project in the admin center and to create/clean-up everything server-side.

Please get in touch with our platform support, creating/deleting projects is an expensive operation and it should be done carefully. I wouldn't recommend to do that for tests (talking from our own experience as we had the same problems).
