### ISSUE TITLE
Inventory Export is not exporting custom fields

### ISSUE THREAD

**Issue by skyriakou** [commercetools/nodejs#1268]
### Support reference number

https://jira.commercetools.com/browse/SUPPORT-5359

### Description

the impex inventory export is not exporting customfields, when the first exported inventory item didn't include them. (the rows and data are simply missing in the file)

If all sku's have the customfield set, than the exported CSV includes the rows.

### Expected Behavior

Inventory Export should export custom fields

### Current Behavior

Inventory Export is not exporting custom fields

### Context

It is difficult to analyse the marketplace partner projects without this information.

### Possible Solution

Add that possibility to specify header template like we have in other exporters??

**Comment by junajan** [comment]
Hello @skyriakou .. I created a PR for this functionality https://github.com/commercetools/nodejs/pull/1277
