### ISSUE TITLE
Setup renovate for coffeescript repos - Daniel

### ISSUE THREAD

**Issue by skyriakou** [commercetools/nodejs#1308]
**What?**
Setup renovate for coffee script repos see list:

- [x] sphereio / sphere-hello-api (Dependency: requests)
- [x] sphereio / sphere-node-product-csv-sync (Dependency: just-extend)
- [x] sphereio / sphere-node-cli (Dependency: just-extend)
- [x] sphereio / sphere-express-pdf (Dependency: moment, handlebars, request)
- [x] sphereio / node-s3-utils (Dependency: debug)
- [x] sphereio / sphere-hello-api-nodejs (Dependency: request)
- [x] sphereio / sphere-product-import (Dependency: just-extend)
- [x] sphereio / commercetools-customer-export (Dependency: handlebars)
- [x] sphereio / sphere-node-utils 
- [x] sphereio / sphere-node-sdk 

If some of the repos are not neccessary - feel free to remove them.

**Why?**
So that we can maintain our Security Updates

For more questions please contact Hajo

**Comment by daern91** [comment]
@skyriakou , can we please check if the following repos can be deleted? They don't seem to be used or developed anymore.

* https://github.com/sphereio/sphere-express-pdf
* https://github.com/sphereio/sphere-hello-api-nodejs
* https://github.com/sphereio/sphere-hello-api
* https://github.com/sphereio/node-s3-utils

**Comment by skyriakou** [comment]
@daern91 

since nobody had anything against deleting the following repos, i would suggest to proceed with archiving them.(make sure that in case of emergencies we can restore the information)

- https://github.com/sphereio/sphere-express-pdf
- https://github.com/sphereio/sphere-hello-api-nodejs
- https://github.com/sphereio/node-s3-utils

Thanks. If u have any questions please let me know.
