### ISSUE TITLE
Changelog not updated

### ISSUE THREAD

**Issue by chrisandrews7** [commercetools/nodejs#1332]
### Description

The [CHANGELOG](https://github.com/commercetools/nodejs/blob/master/CHANGELOG.md) appears to be missing a lot of changes.  

For example the package [sync-actions](https://github.com/commercetools/nodejs/tree/master/packages/sync-actions) is on version [3.3.0](https://github.com/commercetools/nodejs/blob/master/packages/sync-actions/package.json#L7) but the last record in the changelog is for version [1.1.0](https://github.com/commercetools/nodejs/blob/master/CHANGELOG.md#commercetoolssync-actions110-2017-01-19).

When upgrading it makes if very difficult to work out what breaking changes have been introduced.

**Comment by StarpTech** [comment]
Hello, I have the same problem. I recommend to enable lerna changelog generation based on github PR's.

**Comment by daern91** [comment]
Hi everyone, 

We've added the missing breaking changes in #1351. 

Our automated integration with lerna and commitizen had clearly been failing for a while so we'll investigate that too.

Thanks a lot for bringing this up!

**Comment by chrisandrews7** [comment]
Great thanks @daern91

**Comment by chrisandrews7** [comment]
Hey @daern91, I see you did a release today. Do you know when your automated changelog update fix will be going in?

**Comment by daern91** [comment]
Hi @chrisandrews7, there is no date set for it yet but it's in the near-term planning.

**Comment by StarpTech** [comment]
@daern91 this should have super priority because as a customer we have to know the technical impact on our project with every release.

**Comment by daern91** [comment]
cc @skyriakou
