### ISSUE TITLE
Token Auth request data isn't urlencoded and leads to invalid content-length and crash

### ISSUE THREAD

**Issue by StarpTech** [commercetools/nodejs#1333]
Hello,
currently, we are facing with a huge issue where a request against `https://auth.sphere.io/oauth/token` with the `grant_type=refresh_token` flow fails with

```
The refresh token was not found. It may have expired.
```

After hours of investigating the issue is a discrepancy in the content-length header because the data isn't properly encoded in `x-www-form-urlencoded`.

In our case the last char of the refresh token was a `=` and it wasn't encoded in `%3D` which results in 1 bytes instead 3

As a user I definitly expect that the `createAuthMiddlewareForRefreshTokenFlow` will encode my refresh token properly in order to be compliant with the initiated `x-www-form-urlencoded` request.

Workaround:

```js
    createAuthMiddlewareForRefreshTokenFlow({
      host: clientOpts.authUrl,
      projectKey: clientOpts.projectKey,
      credentials: {
        clientId: clientOpts.clientId,
        clientSecret: clientOpts.secret
      },
      refreshToken: encodeURIComponent(refreshToken),
      fetch: clientOpts.fetch
    }),
```

**Comment by skyriakou** [comment]
@StarpTech thanks for your request, we will put this on our backlog. However, if it is urgent we recommend to do a pull request or to create a support request over our [official support channel.](https://jira.commercetools.com/servicedesk/customer/portal/1) Thanks.

**Comment by StarpTech** [comment]
Hello, before closing the issue it's useful to wait for feedback from the creator.
The bug is still there.

The data isn't encoded here

https://github.com/commercetools/nodejs/blob/master/packages/sdk-middleware-auth/src/base-auth-flow.js#L53

```
grant_type=refresh_token&refresh_token=vchXXXX1I= <----
```

**Comment by StarpTech** [comment]
It looks like that the fix wasn't puiblished correctly. The current version on NPM is 5.1.1 but I can only install 5.1.0 with yarn or npm.

**Comment by daern91** [comment]
Hi @StarpTech, I just installed version `5.1.1` successfully from my end. Could you please try it again?

**Comment by StarpTech** [comment]
I can confirm the issue was solved.
