### ISSUE TITLE
[api-request-builder]: Allow user to set fuzzyLevel to  0

### ISSUE THREAD

**Issue by nalchevanidze** [commercetools/nodejs#1348]
### Description

fuzzyLevel checks only against falsy values, that why it throws error on 0 as
argument

### Expected Behavior

```js
fuzzyLevel(0)
```

should reduce fuzziness to 1 or 2 characters
[0 - for texts of one or two characters](https://docs.commercetools.com/http-api-projects-products-search#fuzzy-search
### Current Behavior)

but throws error: 'Required argument for `fuzzyLevel` is missing'

### Possible Solution

- include `0` in boolean expression of  [argument validation](https://github.com/commercetools/nodejs/blob/b308655e923f2576f3fab34703318537ed0eac38/packages/api-request-builder/src/query-search.js#L38)

**Comment by daern91** [comment]
Hi @nalchevanidze,

We've opened a PR for this: #1371

Thanks a lot for writing such a great and detailed issue. This will be released as a patch as soon as it's approved.

**Comment by daern91** [comment]
Fixed in `@commercetools/api-request-builder@5.3.2`
