### ISSUE TITLE
add address id ignored

### ISSUE THREAD

**Issue by rycu** [commercetools/nodejs#1352]
### Description

{{host}}/{{projectKey}}/customers/{{id}}

BODY

```JSON
{
  "version": {{version}},
  "actions": [{
    "action": "addAddress",
    "address": {
      "id": "00000001",
      "country": "DE",
      "firstName": "Barry"
    }
  }]
}
```

RESPONSE

```JSON
{
    "id": "93e8a111-ef0f-417a-bc8f-b7573c70f8da",
    "version": 5,
    "lastMessageSequenceNumber": 5,
    "createdAt": "2019-06-25T08:11:29.991Z",
    "lastModifiedAt": "2019-06-25T08:17:02.012Z",
    "lastModifiedBy": {
        "clientId": "7xZvEksTV5ZXS8EATDaIFdB4",
        "isPlatformClient": false
    },
    "createdBy": {
        "clientId": "7xZvEksTV5ZXS8EATDaIFdB4",
        "isPlatformClient": false
    },
    "email": "foo@bar2.de",
    "password": "Db+DAkNCsxwb/40ZkNWXRmze8jTyixUheE4bvJfFuaQ=$o9pOzIvctWsNUtwvvSmUgq6yUi8UAgkONQQr62vHfyg=",
    "addresses": [
        {
            "id": "L135HC0F",
            "firstName": "Barry",
            "country": "DE"
        }
    ],
    "shippingAddressIds": [],
    "billingAddressIds": [],
    "isEmailVerified": false,
    "key": "myKey2",
    "stores": []
}
```

### Expected Behavior

The specified id is used for the id of the address or at least a hash of this id so that the specified id is usable i other address actions.

### Current Behavior

An alpha numeric id is provided which appears to have no relation to the id specified within the body.  Furthermore, when the specified id is used it fails with "Customer does not contain an address with the id '00000001'."

### Context

creating a fully fledged customer is currently taking multiple calls due to needing created address ids in order to set default addresses.

**Comment by chrisandrews7** [comment]
Essentially trying to do the following:
```json
{
  "version": 1,
  "actions": [
    {
      "action": "addAddress",
      "address": {
        "id": "123",
        "country": "DE"
      }
    },
    {
      "action": "setDefaultShippingAddress",
      "addressId": "123"
    }
  ]
}
```

**Comment by VineetKumarKushwaha** [comment]
Currently after debugging the code I found that we generate the address id from the backend so it means if you pass id or not, our system will always generating new id.

I will sync-up with others developer on this.

**Comment by VineetKumarKushwaha** [comment]
@skyriakou This is CT platform issue, this needs to be fixed at their end. 
As per the document, it shows we can pass id but currently it is being overridden by the generated ID at the CT Platform. So I think this should be raised at their end.

@rycu we have "key" supported in this API so if we want to use some custom id , you can put in key instead of ID.

**Comment by VineetKumarKushwaha** [comment]
@skyriakou  Should I close this issue here ?

**Comment by skyriakou** [comment]
@VineetKumarKushwaha no need to close - I forwarded it to support and they will handle its distribution. Thanks.
