### ISSUE TITLE
Security alerts in sphereio/commercetools repos

### ISSUE THREAD

**Issue by skyriakou** [commercetools/nodejs#1355]
**What?**
Security alerts for the following repos popped up

- [x] sphereio / sphere-brickfox-connector (Dependency: undercore.string)
- [x] sphereio / sphere-node-cli ((Dependency: undercore.string,shelljs)
- [x] sphereio / sphere-product-mapper (Dependency: undercore.string)
- [x] sphereio / sphere-message-processing (Dependency: undercore.string)
- [x] sphereio / sphere-category-sync(Dependency: js-yaml, handlebars)
- [x] sphereio / csv-mapper (Dependency: js-yaml, undercore.string)
- [x] sphereio / underscore-mixins (Dependency: undercore.string)
- [x] sphereio / sphere-product-import (Dependency: js-yaml)
- [x] commercetools / commercetools-sunrise-theme (Dependency: js-yaml)
- [x] commercetools / commercetools-sunrise-php (Dependency: tunnel-agent, sshpk, is-my-json-valid)

If some of the repos are not neccessary - feel free to remove them.

**Why?**
So that we can maintain our Security Updates

For more questions please contact Hajo

**Comment by daern91** [comment]
Hi @skyriakou,

I added renovate to some of them but would like to discuss some of the open ones.

* `sphereio/sphere-brickfox-connector` 
	* this belongs to professional services team, maybe @butenkor could assign it to someone else to fix? I really recommend using [renovate](https://renovatebot.com) as it works great for us.
* `sphereio/sphere-product-mapper`
* `sphereio/sphere-message-processing`
* `sphereio/csv-mapper `
* `sphereio/underscore-mixins`
	* these seem to be super old and possibly not used anymore. Who do we talk to about deprecating them?
* `commercetools/commercetools-sunrise-php` 
	* this does not belong to the node team. Maybe @nikossvnk could handle or direct it to the right person?

**Comment by skyriakou** [comment]
commercetools / commercetools-sunrise-php (Dependency: tunnel-agent, sshpk, is-my-json-valid)
@jenschude  can you have a look?

**Comment by skyriakou** [comment]
sphereio/sphere-brickfox-connector
 @butenkor does it make sense for you take ownership of solve the security alerts here? Thanks

**Comment by skyriakou** [comment]
https://github.com/sphereio/underscore-mixins - @emmenko is this repo still relevant? we have some security alerts popping up , we recommend either using renovate or deprecating the repo since it seems to be very old. What do you think? Thanks.

**Comment by emmenko** [comment]
Btw: in general this is not the "proper" way to handle security updates, as a public issue.

Furthermore, Github security alerts are only visible to the maintainers of the repositories. There are also different "levels" of security alerts. Sometime also there is no "fix" yet to one of the marked packages.

With that said, security updates are important of course, but they should be treated carefully.

Also, a lot of the old "sphereio" package are probably not used anymore.

Hopefully we can handle this sorts of issue better in the future. Thanks

**Comment by emmenko** [comment]
> is this repo still relevant?

All those packages are part of the nodejs tooling, so I can't say much what the current status is. For me, (all) most of the can be deprecated yes. But again, I haven't been involved in those for a long time...

**Comment by skyriakou** [comment]
the following repos were archived : 

- https://github.com/sphereio/csv-mapper
- https://github.com/sphereio/sphere-message-processing
- https://github.com/sphereio/sphere-product-mapper

**Comment by skyriakou** [comment]
sphereio/sphere-brickfox-connector
@butenkor does it make sense for you take ownership to solve the security alerts here? or do you know who else owns this? Thanks!
