### ISSUE TITLE
How to get customObject by container and key?

### ISSUE THREAD

**Issue by StarpTech** [commercetools/nodejs#1358]
Hi, according to the [docs](https://docs.commercetools.com/http-api-projects-custom-objects#get-customobject-by-container-and-key) customObjects can be fetched by container and key property but I can't find it in the SDK.

Doesn't work!
```js
const result = await this.client.execute({
      uri: this.requestBuilder.customObjects
        .parse({
          container,
          key
        })
        .build(),
      method: 'GET'
    });
```

**Comment by daern91** [comment]
Hi @StarpTech, 

You are right. Looks like this is currently not supported. We will treat it as a new feature request and put into our planning.

In the meanwhile, have you figured out a workaround for it already?

**Comment by StarpTech** [comment]
Hi @daern91,
sure, I need to construct it manually everywhere.

**Comment by daern91** [comment]
Hi @StarpTech,

Please have a look at this one #1398

It should resolve this.

Thanks!
