### ISSUE TITLE
return key field value  in state field information for Product

### ISSUE THREAD

**Issue by ilyasf** [commercetools/nodejs#1381]
### Description

When I am making request for Product with state, I want to get information with field state, that contain key field.

### Expected Behavior

I've got an information with key field, like this
```
...productData,
"state": {
        "typeId": "state",
        "id": "2c568852-dc6c-48b4-b54c-7cf30a188bc4",
        "key": "STATE_CONSTANT_KEY"
    }
```

### Current Behavior

I've got an information like this

```
...productData,
"state": {
        "typeId": "state",
        "id": "2c568852-dc6c-48b4-b54c-7cf30a188bc4"
    }
```

I need to make additional request to get the state key, so it's overwork.

### Possible Solution

return key field information, instead of id or just add this field.

**Comment by katmatt** [comment]
@ilyasf You have to expand the state and then you can access the key via `state.obj.key`.
