### ISSUE TITLE
Default auth scope should not be MANAGE_PROJECT

### ISSUE THREAD

**Issue by lojzatran** [commercetools/nodejs#1382]
### Description
When creating new nodejs client, it automatically adds MANAGA_PROJECT scope if you don't provide any.
https://github.com/commercetools/nodejs/blob/1731a8e325135590a64e0540ad9f17cba64c90d9/packages/sdk-middleware-auth/src/build-requests.js#L36

### Expected Behavior
The scope parameter is [optional](https://docs.commercetools.com/http-api-authorization#client-credentials-flow) according to the docs. If no scope parameter is provided in the request, CTP will decide the correct scope depending on the credentials provided. So nodejs library should not put any scope by default.

### Current Behavior
nodejs puts a default scope `manage_project`.

### Context
This issue is related to this PR:
https://github.com/commercetools/commercetools-adyen-integration/pull/76

We're trying to provide smaller scope (only payment and extension related), but it's not possible without explicitly specifying which scopes our credentials have. The scope decision should be done only in MC and after that, nodejs shouldn't change it anymore.

### Possible Solution
Remove the default scope and let CTP decides the scope by provided credentials.

**Comment by daern91** [comment]
FYI @skyriakou
