### ISSUE TITLE
SUPPORT-6705 - Improve error logging, req/resp introspection

### ISSUE THREAD

**Issue by StarpTech** [commercetools/nodejs#1391]
Hello,
when a requests fail e.g with a 500 status code I got this as error message:

```
InternalServerError
Oops. This shouldn't happen.
```
this isn't helpful.

### Expected Behavior
The error message should be much more descriptive e.g including the `correlation-id`, `request-url`, `status-code`.

Beside this fact I would like know how can I access the request/response `headers` of the failed request. The `commerceClient.execute` only returns the `body`.

```
{ body:
   { limit: 20,
     offset: 0,
     count: 5,
     total: 5,
     results: [ [Object], [Object], [Object], [Object], [Object] ] },
  statusCode: 200 }
```

### Proposal

Attach all useful informations to the error object in order to provide a descriptive log message.

**Comment by StarpTech** [comment]
@daern91

**Comment by daern91** [comment]
Hi @StarpTech,

The `500` is thrown from the platform side, we just forward it in the SDK and do not alter it. Anyway, I understand that it is not helpful at all so please forward it to support. 

With regards to the headers, the SDK itself actually forwards those too whenever they are returned. Please see the code [here](https://github.com/commercetools/nodejs/blob/64a99f9e623b104c1dfc2f5d8d2c20de73c86a8e/packages/sdk-client/src/client.js#L55-L64).

To verify that it works I also used this short snippet below to verify.

```
const createClient = require("@commercetools/sdk-client").createClient;
const createHttpMiddleware = require("@commercetools/sdk-middleware-http")
  .createHttpMiddleware;
const fetch = require("node-fetch");

const client = createClient({
  middlewares: [
    createHttpMiddleware({
      host: "https://jsonplaceholder.typicode.com",
      includeResponseHeaders: true,
      includeOriginalRequest: true,
      maskSensitiveHeaderData: true,
      fetch
    })
  ]
});

client
  .execute({ uri: "/todos/1", method: "GET" })
  .then(res => console.log(res));

```

Does this answer your question?

**Comment by StarpTech** [comment]
Hi @daern91 I rechecked the code and it looks like that all informations are attached to the error object https://github.com/commercetools/nodejs/blob/46212ed4f4df2b5129016548a0f6d71cc58eef7a/packages/sdk-middleware-http/src/http.js#L167-L175

What I'm missing is a way to indentify `commercetools` errors. We have a global error handler and to construct proper logs we need to know if its a commercetool error.

The created errors have no base prototype or an property which indicates a commercetools error. I propose to add a property like `isCommercetool` when an error is created.

**Comment by daern91** [comment]
@emmenko, thinking in the same lines here. It _should_ be possible but I have not tested it yet.

**Comment by StarpTech** [comment]
@emmenko @daern91 yes, it's possible thanks for the hint.

```js
const {
  errors: { BadRequest },
  getErrorByCode
} = require('@commercetools/sdk-middleware-http');

console.log(new BadRequest() instanceof getErrorByCode(400)); // true

```

**Comment by StarpTech** [comment]
I recommend an archive of examples for all these use cases the documentation isn't good. :smile:
