### ISSUE TITLE
product-csv-sync doest not work after installed via npm install

### ISSUE THREAD

**Issue by skyriakou** [commercetools/nodejs#1425]
https://jira.commercetools.com/browse/SUPPORT-6958

**Comment by rhm-fyayc** [comment]
hey guys, not sure if it was solved or not, but is related to https://github.com/commercetools/nodejs/issues/1422

**Comment by daern91** [comment]
Hi @rhm-fyayc,

If you reinstall the dependencies it should work. The problem inside "@commercetools/sdk-middleware-auth@5.1.6" got patched in version "5.1.7", and "@commercetools/sdk-middleware-http@5.3.0" in version "5.3.1".

**Comment by rhm-fyayc** [comment]
tks @daern91
