### ISSUE TITLE
https://wiki.commercetools.com/display/SRE/Analysis+of+refresh+token+usage

### ISSUE THREAD

**Issue by skyriakou** [commercetools/nodejs#1426]
https://jira.commercetools.com/browse/SUPPORT-6832

Add documentation:
--> Best practice
--> Why they are using it?- How can they use re use it?- How can we avoid this from happening in the future?

**Comment by daern91** [comment]
https://github.com/commercetools/nodejs/commit/9b69d953d9cdd611da6e44229f2000f8585776e9
