### ISSUE TITLE
[typescript-sdk] Undefined queryArgs properties should not be serialized

### ISSUE THREAD

**Issue by lenkan** [commercetools/nodejs#1454]
### Description

When passing `undefined` to an optional query parameter, it will be serialized as `key=undefined`. In some cases, this is not allowed by the API, so the request will reject with a BadRequest HTTP error. This forces your application code to "clean up" the argument objects before passing them to the typescript-sdk, which is a inconvenient.

```js
// Create ctpClient according to https://commercetools.github.io/nodejs/sdk/api/typescriptSdk.html#usage-example
const ctpClient = ...

const apiRoot: ApiRoot = createApiBuilderFromCtpClient(ctpClient)


// Explicitly specifying the limit works fine
apiRoot
     .withProjectKey({ projectKey })
     .productProjections()
     .get({ 
        queryArgs: {
           limit: 10
        }
     })

// Passing nothing works fine, it uses the default limit
apiRoot     
     .withProjectKey({ projectKey })
     .productProjections()
     .get({ 
        queryArgs: {}
     })

// Passing undefined (as will be a common use case if the value comes from a parameter)
// This will reject with a BadRequest
apiRoot     
     .withProjectKey({ projectKey })
     .productProjections()
     .get({ 
        queryArgs: {
          limit: undefined
        }
     })
```

### Expected Behavior

I expect that if undefined is accepted as a value for a `queryArgs` property, that the SDK should handle that. I expect that the query parameter should be omitted from the URI altogether.

### Context

I'm trying to write utility methods that depends on the `ApiRoot` interface. The utility methods accepts arguments, that are passed through to the ApiRoot. In some cases, the arguments are optional, which results in undefined properties in the `queryArgs`.

### Possible Solution

If this SDK is for use with `nodejs` only, I suggest to use the built in module `querystring` to serialize the query parameters (https://nodejs.org/api/querystring.html#querystring_querystring_stringify_obj_sep_eq_options).

I have a working example here: https://github.com/lenkan/nodejs/commit/33fb7a72475b39834b492f5a0053e67737a08d3a . But since this file is under the `generated` directory, I don't know if this is a valid solution.

If you do not want to use the built in module, you can simply compare any property to `undefined` before pushing it to the queryParams array. I'd be happy to create a PR for that.

**Comment by daern91** [comment]
Tack @lenkan för en välskriven issue!

Let's look into, and figure out how to generate this one, @acbeni.

**Comment by acbeni** [comment]
I know the exact part where, this should be fixed (i m responsible for this atrocity 😅  ), i ll push a fix for it.

**Comment by acbeni** [comment]
I saw the solution, proposed yin the example i think it wouldn't work for two cases:
- when the parameter have non valid url char , which it does sometimes
- for array params, when two values are provided for the same parameter, i think this happens with predicates but not sure
 i ll try to push a fix for it this afternoon.

**Comment by acbeni** [comment]
the fix i suggested is here, if accepted i will include it at the code generator at https://github.com/vrapio/rmf-codegen/ which is used to generate the code here.

**Comment by lenkan** [comment]
@acbeni That solves the problem, so it looks good to me.

But just for reference, `querystring.stringify` will URL encode the query parameter values by default. That is:

```
> qs.stringify({ parameter: "with<>=" })
'parameter=with%3C%3E%3D'
```

For arrays, the default behavior in `querystring.stringify` is to add just add multiple query parameters, one for each value. Which is the same as the current behavior:

```
> qs.stringify({ parameter: ["one", "two"] })
'parameter=one&parameter=two'
```

**Comment by acbeni** [comment]
You solution is much element but wouldn't work either since for example `{{host}}/{{projectKey}}/carts?limit=` is an invalid request since  limit have to be avalid number if specified, that's the only problem i see for now.

**Comment by acbeni** [comment]
closed by https://github.com/commercetools/nodejs/pull/1455
