### ISSUE TITLE
[typescript-sdk] markMatchingVariants is missing from query args type definition

### ISSUE THREAD

**Issue by lenkan** [commercetools/nodejs#1470]
### Description

The type definitions for product projection search is missing the query parameter `markMatchingVariants`. See https://docs.commercetools.com/http-api-projects-products-search#matchingVariant.

The type definition is [here](https://github.com/commercetools/nodejs/blob/master/packages/typescript-sdk/src/generated/client/search/by-project-key-product-projections-search-request-builder.ts#L38):

```typescript
 public get(methodArgs?: {
    queryArgs?: {
      fuzzy?: boolean | boolean[]
      fuzzyLevel?: number | number[]
      staged?: boolean | boolean[]
      filter?: string | string[]
      facets?: string | string[]
      query?: string | string[]
      facet?: string | string[]
      text?: string | string[]
      sort?: string | string[]
      limit?: number | number[]
      offset?: number | number[]
      withTotal?: boolean | boolean[]
      priceCurrency?: string | string[]
      priceCountry?: string | string[]
      priceCustomerGroup?: string | string[]
      priceChannel?: string | string[]
      expand?: string | string[]
    }
    headers?: {
      [key: string]: string
    }
  }): ApiRequest<ProductProjectionPagedSearchResponse> {
```

The RAML spec is also missing the parameter [here](https://github.com/commercetools/commercetools-api-reference/blob/5e8494ab13d84c6fe132c2a4e8f046a3689a0ca5/resources/product-projections-search.raml#L13)

### Expected Behavior

I expect that the parameter should be in the type definition, otherwise I cannot pass it without using some sort of typescript cast.

**Comment by acbeni** [comment]
Thanks for reporting the issue, i already created a followup issue at our API reference, expect a release this week for it.
