### ISSUE TITLE
Remove "*.sphere.io" defaults in favor of no defaults or the new Host name convention

### ISSUE THREAD

**Issue by nkuehn** [commercetools/nodejs#1482]
### Description

To improve the developer experience and easen our support and training burden all existing references to  `*.sphere.io` and `.commercetools.co`  host names should be either removed in favor of not defaulting to a specific region (a common complaint of US customers is that EU is defaulted everywhere) or, if needed for backwards compatibility, be replaced with the new `*.europe-west1.gcp.commercetools.com` notation. 

The dominant place seem to be the generated typescript SDK files, so this could be a relatively easy fix. 

### Expected Behavior

full text search over the repository for ".sphere.io"  and ".commercetools.co" should yield zero results

### Context

https://docs.commercetools.com/release-notes#releases-2020-02-03-aws-and-new-hostnames

**Comment by daern91** [comment]
fixed in: #1507
