### ISSUE TITLE
[sync-actions] changeAttributeOrderByName doesn't work when adding attribute def

### ISSUE THREAD

**Issue by katmatt** [commercetools/nodejs#1492]
### Description

If I add a new attribute definition to a product type, then build the update actions for the product type and send the updates to the backend, then I get the following error:
```json
[{"code":"InvalidOperation","message":"The given attributes must be equal to the type attributes.","action":{"type":"changeAttributeOrderByName","attributeNames":["color","size","weight"]},"actionIndex":1}]
```
Our documentation for the [changeAttributeOrderByName](https://docs.commercetools.com/http-api-projects-productTypes#change-the-order-of-attributedefinitions) update action talk about _current_ attribute defintions and my understanding is that this doesn't include attribute definitions added during the same update request.

### Expected Behavior

The `changeAttributeOrderByName` update action should only be added if the attribute defintions were only reordered, but no defintion was added or removed.

### Current Behavior

The `changeAttributeOrderByName` update action is be added if the order of attribute defintions was changed, even when an attribute definition was added or removed.

### Context

One of our users reported this problem when he tried to update an existing product type.

### Possible Solution

We should only add the `changeAttributeOrderByName` update action when the order of attribute definitions was changed. And not if defintions were added or removed. This of course then requires that an user that wants to update the order has to perform to update requests:

1. the first one to add or remove attribute definitions
2. the second one to correctly order the attribute defintions

**Comment by danrleyt** [comment]
Issue not reproducible anymore.
