### ISSUE TITLE
How to use node sdk-auth to get token after error

### ISSUE THREAD

**Issue by ashishhk** [commercetools/nodejs#1528]
### Support reference number
[Support-8396](https://jira.commercetools.com/browse/SUPPORT-8396)

### Description
I am trying to use node sdk-auth for sunrise.

Initially I try to use an invalid refresh token when that fails I try to get a new token.

I'd expect getting the new token would make an xhr request but what happens is that the getTokenInfo fails with the same error as the refresh token request without making a request. After that you can "run again" as much as you like but the sdk will never make another request and keeps failing with "The refresh token was not found. It may have expired." even though anonymous token flow was set.

```js
import SdkAuth, {
  TokenProvider
} from "@commercetools/sdk-auth";

const tokenProvider = new TokenProvider({
  sdkAuth: new SdkAuth({
    host: "https://auth.europe-west1.gcp.commercetools.com",
    projectKey: "sunrise-spa",
    credentials: {
      clientId: "XXXXX",
      clientSecret: "XXXXX"
    },
    scopes: [
      "manage_my_profile:sunrise-spa create_anonymous_token:sunrise-spa"
    ]
  }),
  onTokenInfoChanged: tokenInfo => {
    console.log("token info changed", tokenInfo);
  }
});

export default () => {
  tokenProvider.fetchTokenInfo = sdkAuth =>
    sdkAuth.refreshTokenFlow(
      encodeURIComponent("invalid refresh token")
    );
  tokenProvider.invalidateTokenInfo();
  return tokenProvider.getTokenInfo().catch(error => {
    console.log("expected this error:", error);
    // refresh token did not work, get a brand new token
    tokenProvider.fetchTokenInfo = sdkAuth =>
      sdkAuth.anonymousFlow();
    tokenProvider.invalidateTokenInfo();
    // this makes no xhr and just fails with previous error
    return tokenProvider.getTokenInfo();
  });
};
```
more detailed code [here](https://github.com/harm-meijer/harm.meijer-commercetools.de) 

### Possible Solution
#1279 could be a good reference point, currently fixed

**Comment by VineetKumarKushwaha** [comment]
This issue is fixed and released in v3.0.8

**Comment by harm-meijer** [comment]
@valoriecarli Is it true that with this version you no longer need to url encode the refresh token? I has an [issue](https://jira.commercetools.com/browse/SUPPORT-8367) with that before and with this version it **doesn't** work if I url encode the refresh token when passing it to `sdkAuth.refreshTokenFlow(`

**Comment by VineetKumarKushwaha** [comment]
@harm-meijer Yes we made a fix where we are now encoding from our side so if you encode then you'd end up with a double encoded refresh token which is why you are getting the issue.
