### ISSUE TITLE
api-requiest-builder: querying orders by orderNumber not supported

### ISSUE THREAD

**Issue by nikolavas** [commercetools/nodejs#1529]
Hi All,

Just realized (or couldn't figure out) that the api-request-builder doesn't support querying single order by orderNumber. Such as requestBuilder().orders.byOrderNumber(orderNumber).build()

As a workaroind I have implemented the following:
uri: `${requestBuilder.orders.build()}/order-number=${orderNumber}`,

**Comment by daern91** [comment]
Hi @nikolavas, 

This was fixed in this PR: https://github.com/commercetools/nodejs/pull/1515

Could you please update to the latest version and try with the above method? 

Thanks!

**Comment by nikolavas** [comment]
Thank you very much for your fast response!
