### ISSUE TITLE
[csv-parser-price] Handle logging appropriately

### ISSUE THREAD

**Issue by wizzy25** [commercetools/nodejs#153]
### Description

Unlike the old repo, status will always be printed to stdout. This can "disturb" the standard output

### Expected Behavior

Logging should be separated from the output content

### Possible Solution

[This](https://github.com/commercetools/csv-parser-price/blob/master/src/cli.js#L54), which is missing in this repo will be a good place to start

**Comment by junajan** [comment]
The default output of the [npmlog](https://github.com/npm/npmlog#logstream) module goes to stderr so we can get parsed prices by removing error logs from output like this:
`CT_JANS_TESTING=keys bin/csvparserprice.js -p jans-testing -i test/helpers/sample.csv 2> /dev/null`

But I agree that we should handle this thing in a more robust way...
