### ISSUE TITLE
[typescript-sdk] Add support for /{projectKey}/shipping-methods/matching-cart

### ISSUE THREAD

**Issue by okkevdeijkGV** [commercetools/nodejs#1536]
### Expected Behavior

I would expect that the new endpoint for the shippingmethods that matches cart is supported:

`/{projectKey}/shipping-methods/matching-cart?cartId=`

https://docs.commercetools.com/http-api-projects-shippingMethods#get-shippingmethods-for-a-cart

### Current Behavior

The current `typescript-sdk` does only have supported for the deprecated endpoint:
`'/shipping-methods?cartId=`

https://github.com/commercetools/nodejs/blob/08b63751b131fbefee9f46c5e89a32f02ea8e749/packages/typescript-sdk/src/gen/client/shipping-methods/ByProjectKeyShippingMethodsRequestBuilder.ts#L45

which gaves a deprecated warning:
`'x-deprecation-notice': [
[start:watch]       "The usage of '/shipping-methods?cartId=' endpoint is deprecated. Please use '/shipping-methods/matching-cart?cartId=' instead."
[start:watch]     ]`

### Context

We cannot use the typescript sdk for using the new endpoint, only for the deprecated one

### Possible Solution

Regenerate the types for shipping methods according to the current situation to have it supported

**Comment by acbeni** [comment]
Hi @okkevdeijkGV 👋 , thanks for reporting the issue. the new version containing the correct path (+other updates), can be found at the latest release of the typescript-sdk https://www.npmjs.com/package/@commercetools/typescript-sdk/v/0.0.20-alpha.0

**Comment by okkevdeijkGV** [comment]
@acbeni Thanks a lot for helping out quickly. Will upgrade our package!

**Comment by okkevdeijkGV** [comment]
@acbeni I have a remark about the implementation, the return value now is `any` and not typed specifically. 
https://github.com/commercetools/nodejs/blob/master/packages/typescript-sdk/src/generated/client/matching-cart/by-project-key-shipping-methods-matching-cart-request-builder.ts#L35

The shipping methods request builder does have the typed `ShippingMethodPagedQueryResponse` which I would expect
https://github.com/commercetools/nodejs/blob/master/packages/typescript-sdk/src/generated/client/shipping-methods/by-project-key-shipping-methods-request-builder.ts#L113

Is there any reason for this or can I propose a PR which fixes this issue?

**Comment by acbeni** [comment]
I tested the path but didnt check for the retur type 😞 . the actual issue is just a type that is missing from commercetools spec https://github.com/commercetools/commercetools-api-reference, i will fix that and regenerate the code.

**Comment by acbeni** [comment]
Ok now its done, please update to https://www.npmjs.com/package/@commercetools/typescript-sdk/v/0.0.2-alpha.0

**Comment by okkevdeijkGV** [comment]
Thanks @acbeni. Works now! Much appreciated.
