### ISSUE TITLE
SdkAuth

### ISSUE THREAD

**Issue by FFawzy** [commercetools/nodejs#1541]
### Description

I was following the example in here
https://commercetools.github.io/nodejs/sdk/api/sdkAuth.html
to use the sdkAuth in my application and I immediately get an error that sdkAuth is not a constructor 
<img width="512" alt="Screenshot 2020-04-27 at 5 33 48 pm" src="https://user-images.githubusercontent.com/24246852/80391380-f20ed700-88ad-11ea-9215-0b351de8427a.png">

Attaching an image of my code.

version used for sdkAuth : “@commercetools/sdk-auth”: “^3.0.6"

**Comment by emmenko** [comment]
If you use CJS with `require` (not ES6 `import`), the loaded object has a `default` property, which is the constructor you are looking for.

```
const SdkAuth = require(‘@commercetools/sdk-auth’).default;
```

**Comment by FFawzy** [comment]
Worked like a charm thanks a lot!
