### ISSUE TITLE
Add recovering when projects are suspended and unsuspended again

### ISSUE THREAD

**Issue by tdeekens** [commercetools/nodejs#1549]
### Support reference number

The commercetools platform is able to suspend projects. A suspension will always be coordinated with projects owners before being carried out. However, it has implication for the Node.js SDK (actually all SDKs).

### Description

Given a project is suspended all access tokens and refresh tokens of this given project are invalidated. The API responds with a HTTP status code of 400, an `invalid_token` and an `error_description` of `[…] project is temporarily suspended  […]`. This needs some alignment with the internal API teams.

The Node.js SDK itself caches an access and refresh token pair from the platform. The cache invalidates the token pair only if it expired based on the given expiry time when fetched.

There are two instances of token caching:

1. [Token Provider](https://commercetools.github.io/nodejs/sdk/api/sdkAuth.html#token-provider): receives an `sdkAuth` instances and caches token info once fetched. It has an `invalidateTokenInfo` but this is not called when requests fail due to an invalid token caused by project suspension.
2. [Auth middlewares](https://github.com/commercetools/nodejs/blob/a34a8cd671a544b249c561eced25f0eff95b4bd5/packages/sdk-middleware-auth/src/base-auth-flow.js#L69): All auth middlewares share a `base-auth-flow` (which itself is a middleware). It uses a token cache to ensure that any middleware downstream has an access token. The token cache is not invalided when a token become invalid before it expired.

Both instances are distinct in their concrete solution needed but similar in their underlying issue. 

The [sdk-middleware-http](https://github.com/commercetools/nodejs/blob/b3e133c3bc435b8108e2390937b73694d3aaf63d/packages/sdk-middleware-http/src/http.js#L28) has the ability to retry requests with backoff and delays. Retries are triggerd with a `503` only however.

A token would also considered being invalid when e.g. it's scopes are insufficient in regards to what a requests intends to load with it. This should unlikely trigger any token cache to be busted. As the request doesn't match what scopes have been requested prior - here we should error.

### Expected Behavior

Any cached token is validated as soon as it is encountered to be invalid due to project suspension. Automatic retrying should likely not occur as suspension can have a longer duration than a configured retry delay.

### Current Behavior

An invalid token due to project suspension remains cached until its expiry date the latest. This yields any request to fail also when a project unsuspended which is when a new token should be fetched. Fetching a new token would happen upon the next request which would fail until the project is unsuspended which then yields a new cached token.

### Possible Solution

For 2. within the middleware chain the status code and error message is used to invalidate the cached token pair.
For 1. `sdkAuth` invokes the `invalidateTokenInfo` when a request fails indicating project suspension

**Comment by anjaliVashisth** [comment]
Migrated to Jira https://commercetools.atlassian.net/browse/DEVX-282
