### ISSUE TITLE
[api-request-builder] Support limit on get requests

### ISSUE THREAD

**Issue by wizzy25** [commercetools/nodejs#160]
### Description

Currently get requests return only 20 per page. If you want more (or less), you have to manually add `&limit=number` to the uri

### Expected Behavior

Should expose a method like `service.limit(number).build()`

### Current Behavior

Something like this has to be done:
```js
const uri = `${service.build()}?limit=100`
```

**Comment by junajan** [comment]
Hello @wizzy25 .. currently there is a `perPage(number)` [method](https://github.com/commercetools/nodejs/blob/master/packages/api-request-builder/src/query-page.js#L54
) which adds a `&limit=` [param](https://github.com/commercetools/nodejs/blob/master/packages/api-request-builder/src/build-query-string.js#L38) to query URL. 

Do we need that `limit(number)` method if we have `perPage`?

**Comment by wizzy25** [comment]
This is done using the `.perPage()` method, hence a non-issue
