### ISSUE TITLE
Optimize client-side @commercetools/sdk-auth

### ISSUE THREAD

**Issue by studentIvan** [commercetools/nodejs#1653]
### Description

A lot of useless code coming with this library:
1. Buffer polyfill
2. Lodash (defaultsDeep)

### Expected Behavior

It works without these libraries or load them only on demand.

### Current Behavior

It works with these libraries and is impossible even to replace them if you use just simple `import SdkAuth, { TokenProvider } from '@commercetools/sdk-auth';` because it uses the UMD version.

### Possible Solution

https://github.com/commercetools/nodejs/pull/1649
https://github.com/commercetools/nodejs/pull/1650
https://github.com/commercetools/nodejs/pull/1651

**Comment by tayzlor** [comment]
+ 1 This prevents this library from being used with build tools such as Vite - which inherently don't support node polyfills in the browser
