### ISSUE TITLE
Fix retry for aborted requests

### ISSUE THREAD

**Issue by kamaz** [commercetools/nodejs#1713]
### Support reference number

N/A

### Description

Aborted requests are not being retried when `enableRetry` is enabled because they reuse the same AbortController for try requests.

### Expected Behavior

Aborted requests are being retried.

### Current Behavior

On abort, subsequent aborts are being aborted instantaneously. 

### Context

When running performance test we see a number of request being aborted which could be due to Commercetools staling-out. 

### Possible Solution

https://github.com/commercetools/nodejs/pull/1712

**Comment by kamaz** [comment]
@jenschude I was wondering if you managed to fix the autorelease. I still don't see the `http` package is published. 

We would like to start using ASAP if possible.

**Comment by jenschude** [comment]
New version has been released today. Sorry for the delay, we are updating the release process so it will be more automated again :)

https://www.npmjs.com/package/@commercetools/sdk-middleware-http
