### ISSUE TITLE
sync-actions: Order number action not generated

### ISSUE THREAD

**Issue by rasmusbe** [commercetools/nodejs#1780]
### Description
When setting order number to an order no action is generated
**Example:**

```js
const {body: order}  = await ctClient
		.orders()
		.withId({ID: "XXX"})
		.get()
		.execute();

	const newOrder = {...order};

	newOrder.orderNumber = "12345";

	console.log(`Original order number: ${order.orderNumber || "N/A"}`);
	console.log(`New order number: ${newOrder.orderNumber || "N/A"}`);

	const syncActions = createSyncOrders().buildActions(newOrder, order);
	console.log(syncActions);
```

### Expected Behavior

`syncActions` should contain the `setOrderNumber` action

### Current Behavior
`syncActions` is empty

### Context

We're setting some initial statuses and order number in an extension and right now we can set the statuses with sync-actions library but the order number is not set.

**Comment by rasmusbe** [comment]
Anyone?

**Comment by ashishhk** [comment]
Hello, my apologies for the delay in response, We'll take a look at the issue and get back to you.

**Comment by VineetKumarKushwaha** [comment]
Looks like we don't support the `setOrderNumber` for now. @ashishhk We need to implement it support it.

**Comment by ashishhk** [comment]
@rasmusbe do you still need it ?

**Comment by rasmusbe** [comment]
It would make sense to include it, but I made my own solution in the customers project.
