### ISSUE TITLE
Investigate Bulk Delete Discount failing for more than 10k 

### ISSUE THREAD

**Issue by ashishhk** [commercetools/nodejs#1823]
Resource Deleter Package requies advanced version of varg library and hence failing for higher size of delete requests

Investigate what would be easier to upgrade the library and what is the impact on other packages of upgrading the library.
Make a decision whether we should split the package to a different repo to upgrade or not.

https://jira.commercetools.com/browse/SUPPORT-18676
https://jira.commercetools.com/browse/SUPPORT-17037
https://jira.commercetools.com/browse/SUPPORT-18703

**Comment by VineetKumarKushwaha** [comment]
Only Issue related to this issue is https://jira.commercetools.com/browse/SUPPORT-18676 . Rests are completed

**Comment by ashishhk** [comment]
Just investigate if its an easy fix without impacting high traffic to platform, otherwise lets talk with Discount team to identify further actions.

**Comment by VineetKumarKushwaha** [comment]
I have tried this locally and got below error

request to https://api.commercetools.com/testproducttypeissue/discount-codes/b8ccaa4f-1a65-4d0d-bd15-5aea1da82195?version=1 failed, reason: connect EHOSTUNREACH <ip>:443 

Looks like this is coming directly from the Merchant Center API. They seems reject API call when specific IP makes a lot of request.

**Comment by tdeekens** [comment]
@VineetKumarKushwaha can you clarify

> Looks like this is coming directly from the Merchant Center API.

How do you see the request comes from the MC API. I lack a bit of context here.

**Comment by VineetKumarKushwaha** [comment]
@tdeekens  `https://api.commercetools.com/testproducttypeissue/discount-codes/b8ccaa4f-1a65-4d0d-bd15-5aea1da82195?version=1` These requests are failing with reason: `connect EHOSTUNREACH :443` when we make 100's of requests in few seconds from the impex and if I am not wrong `api.commercetools.com` is Merchant center API.

**Comment by VineetKumarKushwaha** [comment]
Support ticket is closed. Will reopen if the we see customer tickets again.
