### ISSUE TITLE
Filter out sensitive data from http headers

### ISSUE THREAD

**Issue by butenkor** [commercetools/nodejs#189]
### Description
Use Case:
An API Error occurs during a product-import script and get's logged to the console, which gets forwarded to logentries and displayed there. Since the log contains the HTTP headers, sensitive information like the authorization key will be displayed in logentries.

Sensitive information like the authorization key should be censored automatically.

### Expected Behavior
Should optionally mask sensitive header data

### Current Behavior
Header contains not masked sensitive data like access token.

### Possible Solution
https://github.com/sphereio/sphere-node-sdk/issues/109

**Comment by hisabimbola** [comment]
this is currently supported. You can view more info [here](https://commercetools.github.io/nodejs/sdk/api/sdkMiddlewareHttp.html#named-arguments-options)

I will be closing this issue, please reopen if not what you looking for
