### ISSUE TITLE
Allow to set optional timeout for requests to API

### ISSUE THREAD

**Issue by butenkor** [commercetools/nodejs#190]
### Description
Allow to set custom timeout for long lasting requests

### Expected Behavior
Should accept custom request timeout

### Current Behavior
Custom timeout is not supported

**Comment by chrisandrews7** [comment]
Any update on this one?

**Comment by daern91** [comment]
Hi @butenkor and @chrisandrews7,

Do you mean on the individual request or the client?

**Comment by butenkor** [comment]
@daern91 In our case client would be sufficient as for custom cases one can just create new client with custom timeout.

**Comment by daern91** [comment]
FYI @chrisandrews7 and @smurfpandey, we have an [open PR](https://github.com/commercetools/nodejs/pull/1418) for this now. Feel free to have a look and give comments before we merge.
