### ISSUE TITLE
Commit package-lock.json

### ISSUE THREAD

**Issue by hisabimbola** [commercetools/nodejs#193]
### Description

Since npm officially now uses [package-lock.json](https://docs.npmjs.com/files/package-lock.json) and it's recommended that we commit that, I think it's best we commit it to our packages.

**Comment by wizzy25** [comment]
I'm not sure if we should. As we run CI tests with Node v6 and v4 (with npm v3 and v2 respectively), and personally, I develop on Node v6 and npm v3 to maintain cmpatibility...

**Comment by hisabimbola** [comment]
I am not sure there will be any compatibility issue, if you do not use npm5 it will simply ignore

**Comment by wizzy25** [comment]
As long as there're no compatibility issues, 😃

**Comment by wizzy25** [comment]
This issue has been resolved in #286
