### ISSUE TITLE
Product import should filter out duplicate attributes

### ISSUE THREAD

**Issue by butenkor** [commercetools/nodejs#213]
https://github.com/sphereio/sphere-product-import/issues/101

**Comment by adnasa** [comment]
previous implementation: https://github.com/sphereio/sphere-product-import/pull/103

**Comment by junajan** [comment]
Hello @butenkor .. is this task related to this repo in any way? Because that change with filtering duplicate attribute was done on `sphere-product-import` package not on `sphere-node-sdk` so it should not be needed here.

**Comment by butenkor** [comment]
I think you are right.
