### ISSUE TITLE
Create Flow-typed library definition

### ISSUE THREAD

**Issue by Sikian** [commercetools/nodejs#254]
### Description
In order to integrate this library more consistently, using the flow types for a flow-typed library definition would be of great help. The current definition (by default) exports any for everything, f.e.:
```
declare module '@commercetools/sdk-client' {
  declare module.exports: any;
}
```

Which is a shame, as there is already types defined and this could be done with relative ease.

More info on how to: https://github.com/flowtype/flow-typed/wiki/Contributing-Library-Definitions

Thanks!

**Comment by Sikian** [comment]
@hisabimbola @wizzy25 Is there any update on this issue?

Thanks!

**Comment by hisabimbola** [comment]
@Sikian thanks for bringing this up, definitely a good thing to do.

We will work on it soon but I am afraid I cannot give a date now.
