### ISSUE TITLE
Use caret semver range for development dependencies?

### ISSUE THREAD

**Issue by Siilwyn** [commercetools/nodejs#26]
Let's discuss if we want to use exact versions or semver ranges for the development dependencies.
I would vote for using semver ranges to decrease the amount of Greenkeeper PRs. And feel confident in doing this because we have the dependency lockfile.

**Comment by PhilippSpo** [comment]
👍 When and how do we update the lockfile then?

**Comment by emmenko** [comment]
Yep, someone has to update the lockfile. I would still tend to be careful with that, having greenkeepr PRs might seem a bit spammy but it kind of forces you to check what changed and maybe try out the new version before simply using it.

**Comment by Siilwyn** [comment]
How is it currently being updated? Does that change when we use semver ranges? 😕

**Comment by emmenko** [comment]
Currently we update it manually and commit the changes. So the process is more or less the same.

I'm fine having **some** deps with caret range, and I don't mind having greenkeeper PRs ;)

**Comment by Siilwyn** [comment]
Okay I think it's best to be consistent so let's go with exact versions then. Before closing I'm wondering why `npm-check-updates` doesn't have an exact version.

**Comment by hisabimbola** [comment]
Personally, I feel using caret might make much sense, especially for dev dependencies.

> I'm fine having some deps with caret range, and I don't mind having greenkeeper PRs ;)

...and the PRs don't get merged anyways 🙄
