### ISSUE TITLE
Move csv-parser-price to this repository

### ISSUE THREAD

**Issue by Siilwyn** [commercetools/nodejs#27]
Move the [`csv-parser-price`](https://github.com/commercetools/csv-parser-price/) module to this repository.

Doing this will also require changes to the code of the module and some additional steps:
- [x] Use the new SDK packages as dependencies
- [x] Add a `types` endpoint to the SDK, [PR](https://github.com/commercetools/nodejs/pull/24)
- [x] Get tests passing manually passing credentials
- [x] Add a package to get credentials from the FS
- [x] Check if everything is working as expected manually using the CLI
- [x] Get rid of underscore dependencies
- [x] Convert tape to jest tests
*Got this done by using `jest-codemods`, replacing `it` for `test` and then manually grouping all same-function tests in describe blocks and rewriting `.then().catch()` chains.*
- [x] Remove all root files that already exist in the monorepo root
- [x] Slim down `package.json` fields and development dependencies
- [x] Migrate CLI tests that talk to the API to the integration tests directory
- [x] Refactor arguments to be named
*Accepting one object instead of three unnamed objects.*

**Comment by emmenko** [comment]
Btw: do you plan to use `lerna import` to do so or simply "copy-pasting" it?

**Comment by Siilwyn** [comment]
That is a good question, didn't think about it yet. What would you recommend?
Importing seems nice but I have a doubt about the issue references since they'll probably all break. 🤔

**Comment by emmenko** [comment]
Yeah, I would be careful automatically importing it. If it's a relatively new library we can just manually importing it I guess.

**Comment by Siilwyn** [comment]
Added new tasks to get this done.
