### ISSUE TITLE
Implement a product exporter module

### ISSUE THREAD

**Issue by wizzy25** [commercetools/nodejs#291]
### Description

Implement a module to retrieve commercetools products from the CTP

(Part of a series implementing the rewrite of the [product-csv-sync](https://github.com/sphereio/sphere-node-product-csv-sync) module)

- [x] Expose a public method to receive the output stream
- [x] Recursively get products 
- [x] Write products to the output stream
- [x] Implement a CLI to get input from users
- [x] Add documentation
- [x] Add integration tests

**Comment by hisabimbola** [comment]
@wizzy25 since you are working on this, can you update the description with the features it's going to have. Then you can have a checkbox to check as you implement them.

**Comment by wizzy25** [comment]
@hisabimbola it's been done 👆🏾
