### ISSUE TITLE
Image update action generation breaks with non matching order in `before` and `after`

### ISSUE THREAD

**Issue by tdeekens** [commercetools/nodejs#305]
### Current Behaviour

- When attempting to generate update actions for a product
- and the variants of `before` and `after` are in non-matching order
- then the update action generation fails with the following error

<img width="460" alt="screen shot 2017-09-19 at 13 29 41" src="https://user-images.githubusercontent.com/1877073/30590397-b17b9fb4-9d3e-11e7-9c26-f1b938aeca0c.png">

this error relates to the removal of an image but fails.

### Expected Behaviour

The generated update actions should contain a `removeImage` update action with `url` and `variantId`.

### Context

The problem is more generic and not necessarily unique to the generation of update actions for images. The `sync-actions` package tries to relate a variant of the new and the old but does so by `key`/`index` of the diffed `variants`.

https://github.com/commercetools/nodejs/blob/8efe479be4a667c75ef5dc28a1e5516f1a5e9db2/packages/sync-actions/src/product-actions.js#L181-L185

However, when the variants are not in the same order this fails and the library tries to relate an old with a wrong new variant. Variants can generally not order-able. However, their order can change whenever the master variant changes multiple times for staged data. Imagine the following data coming in

| Diff  | now | before  |
|---|---|---|
|<img width="198" alt="screen shot 2017-09-19 at 13 41 43" src="https://user-images.githubusercontent.com/1877073/30590814-8821e3ba-9d40-11e7-9e9b-74d91f245baa.png">|<img width="140" alt="screen shot 2017-09-19 at 13 41 20" src="https://user-images.githubusercontent.com/1877073/30590850-acb7558e-9d40-11e7-9726-d0bc21787b69.png">|<img width="177" alt="screen shot 2017-09-19 at 13 41 34" src="https://user-images.githubusercontent.com/1877073/30590840-9d3e450e-9d40-11e7-8aa5-84ca19aba89c.png">|

Here an `foreach(variants, key =>` fails to relate `before` and `now` by that `key` making the image update action generation receiving a wrong pair of variants and as a result failing to pluck the `url` meta information.

### Possible Solution

The determination of relating pairs can't be achieved by `key` left alone. It needs more "smarts". For the given input the following applies

| diff | before | now |
|---|---|---|
| 1 | 3 | 1 |
| 1 | 4 | 2 |
| x | 5 | 3 |
| x | 1 | 4 |
| x | 10 | 5 |
| x | 2 | x |

including a removal of `10`. The a for instance `getRelatingPairs`-fn should receive the `diff`, `before`, `now` and generated an array of tuples of indexes to the old and new. E.g. `[[1, 3], [2, 1]]` etc to be used in the `forEach` and then to pick the correct variant of now and before.

This function needs to take the response of diffpatcher into account (ref https://github.com/benjamine/jsondiffpatch/blob/master/docs/arrays.md). Looping over the `diff`, checking for the position if it's a move (e.g. `_3`) and respecting the move (if it's a `["", destination, 3]`.

**Comment by hisabimbola** [comment]
Fixed in #306
