### ISSUE TITLE
Should we build before unit tests?

### ISSUE THREAD

**Issue by wizzy25** [commercetools/nodejs#311]
### Description

Right now, running `npm run test` triggers a build before the tests are run. I can't seem to figure out the necessity of this and would suggest it is removed to speed up test execution (and hence development). 
Let's discuss this here @hisabimbola

**Comment by emmenko** [comment]
It's because of the "local" dependencies of the packages since dependencies in `node_modules` are ignored (hope it makes sense 😅)

**Comment by wizzy25** [comment]
Ah all right, I see it now. Thanks @emmenko. I will close this issue as the "question" has been "answered" 😃
