### ISSUE TITLE
Line Item Status Update: allow more than one transition per line item in CSV

### ISSUE THREAD

**Issue by Oehmi** [commercetools/nodejs#369]
### Description
We want to handle several line item state transitions within one CSV (not possible now) in order to avoid wrong execution of the existing options when updating two transitions at once. Two transitions can currently not be handled within one file, as they are executed in parallel and the order of the transitions may be wrong. 

### Expected Behavior
Both line item state transitions should be within one CSV

### Current Behavior
At the moment it's not possible to have the same line item twice within one CSV, or to have two state transitions for one line item listed in a CSV file. Our customer would like to update two transitions for the same line item at once, in the case that one transition could not be sent before. An automised process is used here, but the line items may be executed in the wrong order, which is very error prone.   

### Possible Solution
Allow multiple transitions for the same lineItemId, put them into one object and sort by actualTransitionDate

(!) check if it works also when sending the update to our API

**Comment by MelNiermann** [comment]
@Oehmi 
Discussed here with the rewe partner management, we will find another solution without this option in the CSV file, so the feature request is for now closed ;) Thanks for checking it.
