### ISSUE TITLE
Add support to fetch shipping methods by location

### ISSUE THREAD

**Issue by damarna85** [commercetools/nodejs#370]
### Description
The API allows us to filter shipping methods by calling the following endpoint:
`/{projectKey}/shipping-methods`
and passing as param the `cartId` we want to use or passing as params the `country`, `region` and `currency` code to get back the shipping methods that can be applied to the cart/location passed. Do you know if this is already available in the sdk somehow? I could not find anything related to this particular case.

Thanks!

### Expected Behavior
Being able to filter shipping methods by cart id or location.

### Current Behavior
Do not find that case.

### Possible Solution
¿Adding that case in the api request builder?

**Comment by wizzy25** [comment]
@damarna85 Currently, there's no support for querying by location (`country`, `region` and `currency`)
It will be put into plan and prioritised accordingly. However, a PR for `query-location` will be more than welcomed

**Comment by junajan** [comment]
Link to API docs http://dev.commercetools.com/http-api-projects-shippingMethods.html#get-shippingmethods-for-a-location
