### ISSUE TITLE
Switch to more powerful middleware system

### ISSUE THREAD

**Issue by dferber90** [commercetools/nodejs#390]
### Description
- suggests to move `client` to a more powerful middleware system (the one of Redux)

This is not of high priority, but I want to open the issue to inform about our failed use-case for the middlewares.

#### Measuring request times
Implementing a timer is a good way to show that a middleware has control over the way up the middleware chain and the way down. While we do not want to use this, it is an easy use-case which highlights some of our requirements.

#### Retrying requests
In the MC we want to retry requests with a different token in case we receive a 401 response. Retrying (with a modified) request based on the response is a common use-case, so I wanted to build it into `client` through a middleware.
This use-case not only means that we need control on the way down, it also means that we should be able to retry the remaining middlewares (the ones invoked by `next`).

### Middleware problems

To me, the middleware system is broken as we only have control of one part of the chain, not the other. This means we can not retry requests depending on the response.

Middlewares can be used to measure the time it takes to complete a request.

```js
next => async request => {
  const start = Date.now()
  const response = await next(request)
  const duration = Date.now() - start
  return Promise.resolve({ ...response, duration })
}
```

or as in Koa

```js
app.use((ctx, next) => {
  const start = Date.now();
  return next().then(() => {
    const ms = Date.now() - start;
    console.log(`${ctx.method} ${ctx.url} - ${ms}ms`);
  });
});
```

In our case we can not do that, as we manipulate the request on the way up, but never hear about the way down. This is solved differently in Redux than it is in Express. It is also different in Koa than it is in Express which indicates that TJ (author of Express and Koa) has learned along the way.

For example https://github.com/koajs/koa#async-functions-node-v76

I think we should actually rewrite `nodejs` to the more powerfull middleware approach instead of using the existing one.

A proper middleware system calls each middleware with the passed value on the way up. Middlewares can manipulate the value on the way up. But each middleware knows about the return value as well on the way down (through the return values of `next()` calls). This gives them a chance to inspect and manipulate the return value.

A middleware can implicitly also invoke the remaining middlewares again by calling `next` multiple times. However it can only return once (unless generators are used).

This also enables usage of non-mutating middlewares.

The redux middleware system also offers a way to run the complete middleware chain again (by using `dispatch`).

### Possible Solution
Move to a middleware system like Redux or like Koa.

**Comment by wizzy25** [comment]
@dferber90 Thanks for creating this issue. I really think it'll be a great way to improve the usability and robustness of the client.

I personally prefer the `async/await` style syntax used in Koa middleware as the code is cleaner, eliminates callbacks and is in my opinion, easier to understand.

However, I don't know much about Redux middleware system, so I cannot compare them both. Especially with regards to calling `next()` multiple times

**Comment by dferber90** [comment]
Glad you like the suggestion!

The difference in middleware between Koa and Redux should not matter. The important distinction here is that currently:
- we start with `request` and `result` at the same time and traverse the middlewares once

While we should ideally:
- start with `request`
- traverse the middlewares once (upward) while giving each middleware the chance to modify the request by passing something different to `next`
- make the actual request in the last middleware (or the library does this)
- traverse the middlewares back down
  - with the result of the request (which would be the return value of the `next(request)` call
  - again giving each middleware the chance to modify the request by returning something different

Allowing each middleware to call `next` multiple times (or even call `dispatch`) implies that making one request using the client can lead to many requests being made. This is useful in case we want to write a middleware which takes a request and traverses all pages. Or one which retries failed requests once before actually failing them. If I remember the code correctly the current implementation/example middleware provides such behaviour already. And it would allow us to easily retry requests in case the authentication token is expired.

I opened https://github.com/commercetools/nodejs/pull/398 to provide an example implementation based on Redux. However the tedious part is to upgrade all existing middleware to the new way.

Maybe it would even be possible to write a function which wraps a middleware of the old style and emits one of the new style. Theoretically this should be possible. But it's most likely only worth it in case there are many customers with custom middleware already. Otherwise I'd rather upgrade the code to keep the code base simple.

**Comment by skyriakou** [comment]
@dferber90  Is this still relevant issue? If not it will be closed. Thanks

**Comment by dferber90** [comment]
We solved it using a different approach not using a middleware.

It's less nice technically but good enough. Let's close this 👍
