### ISSUE TITLE
[api-request-builder] pass projectKey as main option

### ISSUE THREAD

**Issue by emmenko** [commercetools/nodejs#43]
Instead of passing it every time as option of `.build()`, pass it once to `createRequestBuilder`.

> It's a BREAKING CHANGE

**Comment by emmenko** [comment]
Thinking about this a bit more, if we put it in `createRequestBuilder`, **all services** will have the `projectKey` prefixed. This might be fine for most of the services but there might be some that do not need the `projectKey`. In that case, having it in `build` makes it more flexible but kind of verbose to use everytime.

I was thinking maybe of a solution in the middle, where you can explicitly "disable it" on demand.

```js
createRequestBuilder({ projectKey: 'my-project' })
service.users.build({ withProjectKey: false })
```

Any thoughts?

**Comment by Siilwyn** [comment]
Could you give a real-life example of a service which works without the project key? The 'disable' option sounds good to me.

**Comment by emmenko** [comment]
It's only if you provide custom services, the default services will all use the `projectKey` (for now) yes.

**Comment by hisabimbola** [comment]
This is okay for me too, we will go ahead with this...

**Comment by wizzy25** [comment]
Would this implementation be ok, such that the ```createRequestBuilder``` requires the project key and throws if it is omitted, but can then be overridden in the ```service.users.build``` with the explicit ```withProjectKey``` flag to be used to not send the project key to the server (defaults to ```true```)
```js
createRequestBuilder({ projectKey: '' })
// throws an error
```
```js
createRequestBuilder({ projectKey: 'my-project' })
service.users.build({ withProjectKey: false })
// doesn't throw but no projectKey in query
```
```js
createRequestBuilder({ projectKey: 'my-project' })
service.users.build({ withProjectKey: true })
// doesn't throw and projectKey in query
```
```js
createRequestBuilder({ projectKey: 'my-project' })
service.users.build()
// doesn't throw and projectKey in query
```

Any thoughts?
