### ISSUE TITLE
api-request-builder support for type "login" or "customerSignIn"

### ISSUE THREAD

**Issue by chrishelgert** [commercetools/nodejs#438]
### Description
Hello,

i try to implement a login for a commercetools-shop with [api-request-builder](https://github.com/commercetools/nodejs/tree/master/packages/api-request-builder) and i am missing the type "login".

```js
// ...
import { createRequestBuilder } from '@commercetools/api-request-builder'
const requestBuilder = createRequestBuilder({ projectKey })

async function login (email, password) {
  const uri = requestBuilder.login.build() // Uncaught TypeError: Cannot read property 'build' of undefined at <anonymous>
  ...
}
```

### Expected Behavior
[api-request-builder](https://github.com/commercetools/nodejs/tree/master/packages/api-request-builder) should provide an type "login" or "customerSignIn" (https://docs.commercetools.com/http-api-projects-customers.html#authenticate-customer-sign-in)

**Comment by tdeekens** [comment]
Thanks a lot for the feature request and sorry for not having provided it in older versions of the SDK. We added it in the [latest release](https://github.com/commercetools/nodejs/releases/tag/%40commercetools%2Fapi-request-builder%403.7.0). Please upgrade and have a look it works for you as expected.

**Comment by chrishelgert** [comment]
thank you 👍
