### ISSUE TITLE
sdk-middleware-auth is broken in Node.js environment

### ISSUE THREAD

**Issue by Siilwyn** [commercetools/nodejs#46]
### Description
Using the auth middleware does not work in Node.js [because of this piece of code](https://github.com/commercetools/nodejs/blob/master/packages/commercetools-sdk-middleware-auth/src/build-requests.js#L62-L76):
```js
export function getBasicAuth (
  username: string,
  password: string,
  windowObject: Object = window,
): string {
  const basicAuth = `${username}:${password}`
  if (
    windowObject &&
    windowObject.btoa &&
    typeof windowObject.btoa === 'function'
  )
    return windowObject.btoa(basicAuth)

  return new Buffer(basicAuth).toString('base64')
}
```
So `windowObject` falls back to `window` which will be undefined.

### Possible Solution
I propose to follow this approach which Abi found online:
https://nolanlawson.com/2017/01/09/how-to-write-a-javascript-package-for-both-node-and-the-browser/
Funny enough the author created a package for this which we can use: `base64-encode-string`.

**Comment by emmenko** [comment]
Hmm sorry, what is the problem here? I don't get it...

**Comment by Siilwyn** [comment]
@emmenko `windowObject: Object = window` throws an error when used in Node.js thus making this package unusable at the moment.
