### ISSUE TITLE
Remove the appended commercetools before each package directory

### ISSUE THREAD

**Issue by Siilwyn** [commercetools/nodejs#47]
Let's remove the `commercetools-` before each package directory, it's pretty annoying to type in the CLI and makes my editor sidebar unnecessarily wide. :)

Any objections?

**Comment by emmenko** [comment]
🤔 I have to check if it works in all places. I'll take over this.

**Comment by Siilwyn** [comment]
Done by the looks of. 🎣

**Comment by emmenko** [comment]
Yep, forgot to link it here #59 :)
