### ISSUE TITLE
[http-user-agent] Avoid using "new Function" to check browser environment

### ISSUE THREAD

**Issue by emmenko** [commercetools/nodejs#479]
### Description
Using `new Function` is [considered harmful](https://developer.chrome.com/extensions/contentSecurityPolicy#JSEval) and is blocked by CSP.

Since [we are using it](https://github.com/commercetools/nodejs/blob/master/packages/http-user-agent/src/create-user-agent.js#L5-L22) to check if the code runs on nodejs or browser, can find a better solution, thus allowing CSP to be happy about it.

**Comment by emmenko** [comment]
@tdeekens do you have a suggestion how we can easily check if the env is nodejs or browser?

**Comment by tdeekens** [comment]
I used something on [DOMPurify](https://github.com/cure53/DOMPurify) which I managed to get by @cure53. Let me check.

**Comment by tdeekens** [comment]
Seems like we went for `if (!window || !window.document || window.document.nodeType !== 9) {...}` to detect if we run in the browser.

**Comment by tdeekens** [comment]
Let me spin up a PR.
