### ISSUE TITLE
Add support for  a `correlationId` on each request to `sdk-client`

### ISSUE THREAD

**Issue by tdeekens** [commercetools/nodejs#551]
### Description

This commercetools platform supports specifying correlation ids on each request. Whenever no correlation id is specified the platform will generate one for the incoming request right after it hit the API. This correlation id is then passed through the system (like correlation ids are) for request tracing at different stages. 

Other SDKs already support specifying a custom correlation id. The id is then passed as a request header `x-correlation-id` (string with max 256 characters). The commercetools API then takes the specified id over generating a new one. This allows clients to "bridge" request tracing from an external system into our APIs. 

Correlation ids are becoming needed for the merchant center to:

1. Trace failing requests from e.g. Sentry in internal commercetools logging tools
2. Make known that a specific request comes from the merchant center (as prefix)
3. Allow for anonymous user tracing/identification to be aware which user modified data in the merchant center

From these the requirements are:

1. Add a `sdk-middleware-correlation-id` (suggestion)
2. Allow configuration and prefixing of the correlation id
3. Send the generated correlation id from the middleware as a header

**Comment by tdeekens** [comment]
I will mention @wizzy25, @emmenko, @cneijenhuis and @idamia for awareness as some brought the topic towards me and some should engage in elaborating a possible solution.

**Comment by emmenko** [comment]
Nice! Should the custom correlation-id be in a specific format?

**Comment by tdeekens** [comment]
> Nice! Should the custom correlation-id be in a specific format?

To my understanding is can be any string of maximum 256 characters long. I would not expect it being validated to be unique due to cost of doing that.

1. Without the `sdk-middleware-correlation-id` used
  - Then the commercetools platform would still generate it
2. With adding the `sdk-middleware-correlation-id`
   2.1 When not configuring it
     - It would generate a uuid4 by default
   2.2 When configuring it (e.g. passing in a `generate`-fn
     - Then it would use that fn to generate

I see two implementation paths mainly for the configuration:

1. Complete control via a `onGenerate` callback being called each time a correlation id should be generated
2. Adding `prefix` and `postfix` parameters which would just be prepended or appended to the uuid4 which would be generated in any care

**Comment by wizzy25** [comment]
Nice one @tdeekens. I think adding a middleware to generate the correlation id will be the way to go. 
Just one question; in the event that (almost) any string will do, will it be better to pseudorandomly generate a `uuid` for each request or to add some more specific identifier (related to the user agent) generating the request?
cc @daern91

**Comment by cneijenhuis** [comment]
The default implementation used by the JVM and PHP SDKs generates a correlation id in the following format:

`$projectKey/$uuid`

That can, of course, be overridden as one wishes. But it would be nice if all SDKs would generate the same default correlation id.

**Comment by cneijenhuis** [comment]
Also, HTTP Headers are case-insensitive, so it doesn't really matter, but the backend returns the header as `X-Correlation-ID`.

**Comment by emmenko** [comment]
I think the middleware should require to provide a correlation-id (and throw if not) and not generate one by default, because the API already does that.
