### ISSUE TITLE
[Sync-actions] Proper order of product update actions

### ISSUE THREAD

**Issue by wizzy25** [commercetools/nodejs#589]
### Description
Product update fails if a new variant is added and a `SameForAll` attribute is updated at the same time.
This occurs because a variant is added with the new attribute value while the old value still exists on the API. And as all attributes must be the same, an error occurs.

### Expected Behaviour
Attribute update actions should be built before (add) variant action(s)

### Current Behaviour 
The `addVariant` action is built before the `setAttribute` and `setAttributeInAllVariants` actions, causing the update failure

### Context
As an example of how it should be done (how it's done in the node SDK), see [here](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/sync/product-sync.coffee#L44)

**Comment by butenkor** [comment]
Ordering of actions was already a topic for old SDK. It seems that here we might hit also the issue with `addVariant` vs `removeVariant` as remove has to be always executed first. For more details see here:
https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/sync/product-sync.coffee#L45
