### ISSUE TITLE
Automate nested dependency updating

### ISSUE THREAD

**Issue by Siilwyn** [commercetools/nodejs#62]
### Description
Currently we use Greenkeeper but it does only update the dependencies in the root package.json. The `check-updates` npm script solves this but does not seem to be triggered automatically anywhere. We can trigger it after CI tests so every time before a PR is merged the dependencies need to be updated. Another option is using [Travis new cron jobs](https://docs.travis-ci.com/user/cron-jobs/) in combination with [Renovate](https://github.com/singapore/renovate)

**Comment by wizzy25** [comment]
closed by #416
