### ISSUE TITLE
API request builder defaulting to different staged values

### ISSUE THREAD

**Issue by daern91** [commercetools/nodejs#653]
### Description
When using the [api-request-builder](https://commercetools.github.io/nodejs/sdk/api/apiRequestBuilder.html) to query [productprojections](https://docs.commercetools.com/http-api-projects-productProjections.html#query-productprojections) we set the default `staged` value to **false** when running once (by not adding it at all), and then to **true** on all subsequent calls to the `.build()` method. 

This doesn't seem like the intended behaviour since we get different results. So, my question is, which one do we actually want to default to? 

Personally, I think defaulting to the first behaviour is the most coherent since it will just follow the API. This way people can opt-in by using the `.staged(true)` method and we won't have to update all of our tests.

Please have a look at the current behaviour below

```js
const a = require("@commercetools/api-request-builder");

const requestBuilder = a.createRequestBuilder({
  projectKey: "test"
});
const productProjectionsService = requestBuilder.productProjections;

console.log(productProjectionsService.build());
console.log(productProjectionsService.build());
console.log(productProjectionsService.build());
// /test/product-projections
// /test/product-projections?staged=true
// /test/product-projections?staged=true
```

Ping @emmenko @adnasa @tdeekens

**Comment by tdeekens** [comment]
1. I think we should pick what causes the least breaking changes for consumers (if even at all). 
2. We should (@adnasa) verify that all parts of our UI set staged to `true` explitely if we we decide to default this to `false`
3. Can we have a PO's opinion of what the most frequently used use case is?

**Comment by adnasa** [comment]
1. I think we should conform with the API (default to `false`)
2. We don't use `productProjections` in our UI, so there is nothing to check
3. I recommend that we get in touch with the different teams in CT and discuss this issues. I don't think PO's could provide any valuable input

**Comment by tdeekens** [comment]
After a night of sleep I also strongly lean towards staged=true by default.

**Comment by adnasa** [comment]
I'd like to discuss and hear out why 😳

**Comment by adnasa** [comment]
I want to correct myself here. 
We do use `productProjections`, although we have __explicitly__ specified `stage: true|false` everytime.

Good from my side

**Comment by tdeekens** [comment]
Cool so for the MC it won't matter.

Then it's either of two choices:

1. Conform with the API: staged=false
2. Conform with "kind of" what happened before: staged=true

Not for us to decide. It's also a product decision.
