### ISSUE TITLE
SDK middleware fails when given a host that ends with a slash

### ISSUE THREAD

**Issue by Siilwyn** [commercetools/nodejs#67]
### Description
Passing `https://api.sphere.io/` vs. `https://api.sphere.io` makes a difference.

### Expected Behavior
Both should work the same.

### Current Behavior
My guess is it ends up with a double slash when appending things to the host URL.

### Context
I used the URLs that are given at the dev.commercetools.com documentation which failed. Confirmed this for `sdk-middleware-http`.

### Possible Solution
Merge slashes if needed.

**Comment by emmenko** [comment]
PS: also for `auth` middleware then ;)
