### ISSUE TITLE
Some limitations of the sdk-auth-middleware when used in SPA+Apollo

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/nodejs#718]
### Description

As you may know, in SUNRISE (as Single-Page Application) we are using Apollo to communicate with the commercetools' GraphQL endpoint, so we don't use the Node.js SDK. But to avoid duplicating all the authentication logic, we are using the sdk-middleware-auth to fetch/refresh the different tokens, which we then connect to Apollo as a middleware (https://github.com/commercetools/sunrise-spa/blob/3dd595841630907f2d5efb63b355b2b8d763ffa1/src/apollo.js#L23-L29). It works well, even though it might be a bit unnatural.

Of course it's the SDK's middleware that manages the token and we don't have any access to it. That was not an issue with the Credentials Flow, but with the Password Flow that becomes really problematic because we have no way to keep the refresh token in the storage, to prevent the user from being logged out when s/he reloads the app (you can test it here: https://sunrise.netlify.com/).

So in short, the problems are:
1) Refresh tokens are lost on reloading the app, so it's not usable. Allowing to use a custom storage would be a solution.
2) It would be great to have authentication support (fetch/refresh token) designed for being used without the SDK, as sometimes other clients, such as Apollo, offer so much more specialized support that our clients are not meant to beat. Either extracting the logic into a non-middleware type of library or exporting some of the functions would be a big improvement.

Could you help us? Specially point num. 1 is high priority IMO as I don't think it's usable for anybody at the moment. Num. 2 is a really nice improvement that would allow commercetools to actively support using Apollo for GraphQL-based apps (and other clients as well).

### Expected Behavior

1) When reloading a single-page application using the sdk-auth-middleware, you should stay logged in.
2) When implementing an application where I don't want to use the SDK (e.g. I want to use Apollo), I still want commercetools to provide a tool that takes care of the authentication.

### Current Behavior

1) When reloading, it logs out, as the refresh token is lost and I have no way to get it.
2) I need to fake a request and capture the token with a Promise, which is not pretty (but it works).

### Context
I'm trying to build a single-page application using Apollo to directly connect to our GraphQL endpoint. As it's a SPA, we need to use the /me endpoints to access customer/cart information.

### Possible Solution
1) Allow to access the internal store or define where the tokens should be stored.
2) Extract the functionality into another library that is not acting as middleware, and call it from the middleware.

**Comment by junajan** [comment]
Hello @lauraluiz, @daern91 
I think that it is a wrong when people has to write their own process for retrieving token in every app which wants to access CTP API and that we should provide some way how to do it through our SDK.

Also, I don't know if it is a correct way to extend auth middleware module with this feature because it would not be a middleware anymore. Therefore I propose to create a new module in monorepo which would take `authorization flow` type (password flow, client credentials flow, anonymous flow and refresh password flow) together with necessary data and it would use our auth middlewares to fetch the token.

Actual saving of the token to some store should be done by app itself together with other tokens it has because otherwise we would have to cover multiple environments (browser app, server side app, mobile app...) where the user would want to save the token.

Please let me know what do you think about it..

**Comment by lauraluiz** [comment]
Same shared thought about the module. That's definitely the way.

Regarding the token, notice that the issue 1) is that we don't have access to the "refresh token". I can get the "auth token", but not the "refresh token", which is kept inaccessible inside the middleware and is what allows users to stay in the page forever.

**Comment by junajan** [comment]
Hello @lauraluiz @daern91 .. I put together some idea how the new module should work.

## Initial info
Currently supported [authentication flows](https://docs.commercetools.com/http-api-authorization.html#hosts) by our SDK are:
 - client credentials flow (clientId, clientSecret)
 - password flow (userName, userPassword)
 - refresh token flow
 - anonymous session flow

Special actions:
 - OAuth2 Token Introspection

## Design
I would vote for creating some class which can be linked to your project and takes a configuration (`{ clientId, clientSecret, ... }`) and then it allows you to use authentication methods based on your auth. strategy.

Note: Configuration was taken from original [middleware-auth config objects](https://commercetools.github.io/nodejs/sdk/api/sdkMiddlewareAuth.html).

```js
import CtpAuth from 'sdk-auth'

(async () => {
   /**
    * Class constructor takes a common configuration
    * which is being used across all auth. flows
    */
    const authClient = new CtpAuth({
      authUrl: 'https://auth.commercetools.com', // US: https://auth.commercetools.co/
      projectKey: 'project-key',
      scopes: [ // list of scopes, default: manage_project:{projectKey}
        'view_products:{project-key}',
      ],
      credentials: {
        clientId: '123',
        clientSecret: 'secret',
      },
      fetch, // (Function): A fetch implementation - optional.
      // see description here https://commercetools.github.io/nodejs/sdk/api/sdkMiddlewareAuth.html#named-arguments-options
    })
    
    // Methods:
    // authClient.clientCredentialsFlow()
    // authClient.passwordFlow(userCredentials)
    // authClient.refreshTokenFlow(token)
    // authClient.anonymousFlow(anonymousId)
    // authClient.introspectToken(token)

    await authClient.clientCredentialsFlow()
    // {
    //   "access_token": "vkFuQ6oTwj8_Ye4eiRSsqMeqLYNeQRJi",
    //   "expires_in": 172800, // seconds (2 days)
    //   "scope": "manage_project:{projectKey}",
    //   "token_type": "Bearer"
    // }

    await authClient.passwordFlow({
      username, // string
      password, // string
    })
    // {
    //   "access_token": "v-dZ10ZCpvbGfwcFniXqfkAj0vq1yZVI",
    //   "expires_in": 172800,
    //   "scope": "view_products:{projectKey} manage_my_orders:{projectKey} manage_my_profile:{projectKey}",
    //   "refresh_token": "OWStLG0eaeVs7Yx3-mHcn8iAZohBohCiJSDdK1UCJ9U",
    //   "token_type": "Bearer"
    // }

    await authClient.refreshTokenFlow(token)
    // :-( no example - https://docs.commercetools.com/http-api-authorization.html#refresh-token-flow

    await authClient.anonymousFlow(anonymousId)
    // {
    //   "access_token": "v-dZ10ZCpvbGfwcFniXqfkAj0vq1yZVI",
    //   "expires_in": 172800,
    //   "scope": "view_products:{projectKey} manage_my_orders:{projectKey} manage_my_profile:{projectKey}",
    //   "refresh_token": "OWStLG0eaeVs7Yx3-mHcn8iAZohBohCiJSDdK1UCJ9U",
    //   "token_type": "Bearer"
    // }

    // Introspection:
    await authClient.introspectToken(token)
    // {
    //   "active": true,
    //   "scope": "view_products:background-test-26",
    //   "exp": 1501158800852
    // }
    // or
    // {
    //   "active": false
    // }
})
```

Unfortunatelly there is currently no way how to get all these data (`expiration`, `refresh_token`, ..) whithout modifying `sdk-middleware-auth`. Without a bigger change - we can get only an `access_token` right now.

So we have following options now:
1) decide to export only `access_token` without methods for refreshing and introspecting it
2) complicated but imho more correct way - move [fetching auth token](https://github.com/commercetools/nodejs/blob/master/packages/sdk-middleware-auth/src/base-auth-flow.js#L36) process as well as [building requests](https://github.com/commercetools/nodejs/blob/master/packages/sdk-middleware-auth/src/build-requests.js) to this new module and then use it in middleware
3) less complicated but less elegant - export and modify features for building and sending auth requests in the middleware so we can use them in the new module
3.5) modify and export some features from the auth middleware so users can use it on their own (this would be pretty clumsy as they would have to pass and mock a lot of stuff - eg. request/response objects..)

If we want to build this for more customers, I would vote for option number 2) as it is more elegant and better scalable solution.

Please share your thoughts..

**Comment by lauraluiz** [comment]
The code looks good, just what we need :)
Regarding the options:
1. Definitely not, the fact that we cannot access the refresh token is a bug, so it should be solved as higher priority.
2. My personal favourite, it solves both issues the correct way. This solution will also be better in the long run. And the middleware is a black box from the outside, and this allows it to remain the same.
3. As you said, it breaks the black box effect and conflicts with the meaning of middleware.

So yeah, 2 no doubt.

**Comment by junajan** [comment]
Hello @lauraluiz .. please check the docs here https://github.com/commercetools/nodejs/blob/master/docs/sdk/api/sdkAuth.md try the new `@commercetools/sdk-auth` module and let us know if there is anything we should change

**Comment by lauraluiz** [comment]
Hi @junajan, thanks for the changes. I've checked the documentation and the purpose of the module goes into the right direction, but I'm missing half of the logic the middleware offered me, at least what the documentation says.

The middleware not only made the request (which the module does) but also kept the auth token alive by refreshing it in a timely manner (which the module doesn't do). We shouldn't let that logic to the clients, otherwise we would end up with all repeated code.

Then it comes the issue of the refresh token, which we should be able to access and set.

**Comment by junajan** [comment]
Hi @lauraluiz .. currently `sdkAuth` methods will call API and generate a new token for every auth flow request. And I understood that you want something that will put token to cache and reuse it in the next call and also refresh it after it expired.

There is, however, one thing which I am not sure about - I think that this module should not care about all possible stores (memory, localStorage, cookies, databases, sessions) - this should be maintained by the project itself.

So I can think of some enhancement to the current implementation where you could provide a token info (access/refresh_token, expires_in, ..) from your store as well as some event handler function which would be called when the new token is loaded so you can save it back to your store. There would be also a flag which would turn on/off this functionality (reusing token), for example like this:
```js
sdkAuth = new SdkAuth({
  // ... config as before,

  // should we cache and reuse generated tokens?
  cacheToken: true,
  
  // init cache value with token info
  tokenInfo: {
  	access_token, refresh_token, expires_in,...
  },
  onTokenLoaded: (tokenInfo) => {
  	// method called when the new token is loaded
  	// you can save token to your store and provide it next time you initiate SdkAuth
  },
})

sdkAuth.passwordFlow({ ... }) // will retrieve token from API
sdkAuth.passwordFlow({ ... }) // will retrieve token from internal cache
sdkAuth.clearTokenCache() // will clear internal cache
sdkAuth.passwordFlow({ ... }) // will retrieve token from API
// wait for token to expire
sdkAuth.passwordFlow({ ... }) // will retrieve token from API because expires_in is smaller than current date
sdkAuth.passwordFlow({ ... }) // will retrieve token from internal cache
```

I am not sure if this is the best solution so please let me know what do you think about it @lauraluiz @daern91

**Comment by junajan** [comment]
Hi @lauraluiz .. have you had a chance to think about what should be done with this ticket? (cc @daern91 )

**Comment by junajan** [comment]
Hello @lauraluiz, Hi @daern91 .. please check this code draft which should take tokenInfo obtained from one of the authFlows and it the token get expired, it will automatically refresh it and provide new `access_token`:

```js
/**
 * Class for refreshing token if it got expired 
 */
class TokenProvider extends EventEmitter {
  // tokenInfo = {
  //   "access_token": "...", // optional - if not provided, getToken() will immediately refresh token using refresh_token 
  //   "expires_in": 172800,  // optional - if not provided, getToken() will immediately refresh token using refresh_token
  //   "refresh_token": "..." // optional - if not provided, refresh process will throw error
  // }
  constructor(tokenInfo) {
    this.tokenInfo = null
    
    this.setTokenInfo(tokenInfo)
  }

  _isTokenExpired(tokenInfo) {
    // compare expires_in, check if access_token is set
  }

  setTokenInfo(tokenInfo) {
    if(!tokenInfo['access_token'] || !tokenInfo['refresh_token'])
      throw new Error('At least one of "access_token" or "refresh_token" has to be provided')
    
    this.tokenInfo = tokenInfo
    this.emit('onTokenInfoChanged', tokenInfo)
  } 
  
  getTokenInfo() {
    return this.tokenInfo
  }
  
  async refreshToken(tokenInfo) {
    // call refresh auth flow
  }
  
  async getToken() {
    const oldTokenInfo = this.tokenInfo
    
    if(this._isTokenExpired(oldTokenInfo)) {
      const newTokenInfo = await this.refreshToken(oldTokenInfo)

      this.setTokenInfo(newTokenInfo)
      this.emit('onTokenRefreshed', newTokenInfo, oldTokenInfo)
    }
    
    return this.getTokenInfo(this.tokenInfo)['access_token']
  } 
}

/**
 * Example usage:
 */
const tokenInfo = {
  "access_token": "...",  
  "expires_in": 172800, 
  "refresh_token": "..."
}
const tokenProvider = new TokenProvider(tokenInfo)

try {
  const token = await tokenProvider.getToken()
} catch (err) {
  if(err.code === 401)
    console.error('Unauthorized', err)
  else
    console.error('General error', err)
}


/**
 * Version without using eventEmitter dependency:
 */
class TokenProvider {
  constructor(tokenInfo, {onTokenInfoChanged, onTokenRefreshed}) {
    this.onTokenInfoChanged = onTokenInfoChanged
    this.onTokenRefreshed = onTokenRefreshed
    // ...
  }

  // ...
}
```
