### ISSUE TITLE
Error while exporting products

### ISSUE THREAD

**Issue by VasumathiJayakumar** [commercetools/nodejs#726]
### Support reference number

SUPPORT-3820

### Description

When exporting the products using the product export command we get the following error. 

`ERR: Malformed parameter: where: Invalid UUID string: `

### Expected Behavior

The products are exported as CSV

### Current Behavior

`{"level":30,"time":1535531180734,"msg":"Starting conversion","pid":579,"hostname":"express-impex-5c8d89f694-4rkg2","v":1}
{"level":50,"time":1535531181085,"msg":"Malformed parameter: where: Invalid UUID string: ","pid":579,"hostname":"express-impex-5c8d89f694-4rkg2","type":"Error","stack":"BadRequest: Malformed parameter: where: Invalid UUID string: \n    at createError (/app/node_modules/@commercetools/product-json-to-csv/node_modules/@commercetools/sdk-middleware-http/dist/commercetools-sdk-middleware-http.cjs.js:182:29)\n    at /app/node_modules/@commercetools/product-json-to-csv/node_modules/@commercetools/sdk-middleware-http/dist/commercetools-sdk-middleware-http.cjs.js:276:25\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)","code":400,"statusCode":400,"status":400,"message":"Malformed parameter: where: Invalid UUID string: ","originalRequest":{"uri":"/example-data-9/channels?where=id%20in%20(%22%22)","method":"GET","headers":{"Authorization":["Bearer ********"],"User-Agent":"commercetools-js-sdk Node.js/8.11.4 (linux; x64) @commercetools/product-json-to-csv/2.1.1"}},"headers":{"server":["nginx"],"date":["Wed, 29 Aug 2018 08:26:21 GMT"],"content-type":["application/json; charset=utf-8"],"content-length":["177"],"server-timing":["projects;dur=2"],"x-correlation-id":["projects-b9b64d0f-4fda-4f45-9c16-1862cd0de526"],"x-served-by":["api-gce-bf772e57.sphere.prod.commercetools.de"],"x-served-config":["sphere-projects-ws-1.0"],"access-control-allow-origin":["*"],"access-control-allow-headers":["Accept, Authorization, Content-Type, Origin, User-Agent"],"access-control-allow-methods":["GET, POST, DELETE, OPTIONS"],"access-control-max-age":["299"],"via":["1.1 google"],"alt-svc":["clear"],"connection":["close"]},"body":{"statusCode":400,"message":"Malformed parameter: where: Invalid UUID string: ","errors":[{"code":"InvalidInput","message":"Malformed parameter: where: Invalid UUID string: "}]},"name":"BadRequest","v":1}
ERR: Malformed parameter: where: Invalid UUID string: `

### Context

The customer could not export products.

**Comment by junajan** [comment]
I found out that when [resolving channels](https://github.com/commercetools/nodejs/blob/master/packages/product-json-to-csv/src/main.js#L227) after we filter out IDs which were already cached, we should check whether we have any IDs left and if not, we should not perform any API request because we would be fetching channels with this predicate:
```js
id in ("")
```
Which will end up with this error:
```js
ERR: Malformed parameter: where: Invalid UUID string:
```
