### ISSUE TITLE
[sdk-http] Support gzip compression for http requests

### ISSUE THREAD

**Issue by emmenko** [commercetools/nodejs#79]
Seems to be easy to enable it for `node-fetch`.

![image](https://cloud.githubusercontent.com/assets/1110551/22862144/447d6346-f129-11e6-9755-13028a4879c1.png)

Fixes sphereio/sphere-node-sdk#196

**Comment by PhilippSpo** [comment]
Shouldn't we be using [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch)?

**Comment by emmenko** [comment]
We are, but window.fetch doesn't support apparently. 
Eg: https://github.com/github/fetch/issues/337

**Comment by emmenko** [comment]
And isomorphic-fetch is nothing more then a library proxy which uses node-fetch or window.fetch

**Comment by wizzy25** [comment]
Just looked into this and gzip/deflate compression is already enabled by default. As such, this is a non-issue. @emmenko @PhilippSpo @hisabimbola

**Comment by hisabimbola** [comment]
Since it's enabled by default, this issue is resolved.

Though it can be improved by adding a flag to turn it off if the feature is not desired 🤔
