### ISSUE TITLE
Enforce git commit message

### ISSUE THREAD

**Issue by Siilwyn** [commercetools/nodejs#84]
### Description
After reading [this](https://github.com/commercetools/nodejs/pull/74#issuecomment-279774679) it got me thinking on how to enforce the git commit message. It seems that only with GitHub Enterprise you can define server side hooks *but* what we can do is: only allow rebasing PRs that pass the CI and adding a commit message check at the CI. Shouldn't be to difficult to do and prevents any possibility of human error.

Thoughts? @hisabimbola @emmenko

**Comment by Siilwyn** [comment]
💭  We can add a npm script that does master pull > soft rebasing > npm run commit. To make the workflow a bit easier.

**Comment by adnasa** [comment]
yeah I would go for that approach too, @Siilwyn

**Comment by hisabimbola** [comment]
@Siilwyn is this
> We can add a npm script that does master pull > soft rebasing > npm run commit. To make the workflow a bit easier.

I don't quite understand how this is going to work? CI or after merging?

**Comment by Siilwyn** [comment]
@hisabimbola let's me try to explain by example:
1. Open PR with some commits
2. CI checks PR including the commit message format
3. ...
4. PR ready to merge, only way to merge is rebasing
5. Run `npm run pr` locally > fill in commit message
6. Force push to PR branch
7. Rebase PR

**Comment by hisabimbola** [comment]
There is need to squash some commits, how to that come in if the only way to merge is rebasing.

Also when PR is ready to merge, what will you be committing?

**Comment by Siilwyn** [comment]
> There is need to squash some commits, how to that come in if the only way to merge is rebasing.
The 'squashing' is done locally.

> Also when PR is ready to merge, what will you be committing?
In the end you will commit the commit that was made in step 5.

**Comment by wizzy25** [comment]
With the move away from `semantic-release` in #352, this issue is no longer relevant
