### ISSUE TITLE
Update docs after a successful build on master

### ISSUE THREAD

**Issue by Siilwyn** [commercetools/nodejs#89]
Docs on https://commercetools.github.io/nodejs/sdk/api/sdkMiddlewareAuth.html are out of date? Host has no default value anymore.
https://github.com/commercetools/nodejs/pull/56#issuecomment-277205632
@emmenko

**Comment by wizzy25** [comment]
Repo documentation is up-to-date https://github.com/commercetools/nodejs/blob/master/docs/sdk/api/sdkMiddlewareAuth.md#createauthmiddlewareforclientcredentialsflowoptions

But published documentation is behind
https://commercetools.github.io/nodejs/sdk/api/sdkMiddlewareAuth.html#named-arguments-options

**Comment by hisabimbola** [comment]
Can you create a PR for this @wizzy25 ?

**Comment by Siilwyn** [comment]
Would be nice if @emmenko could shine some light on this first, he probably knows what's going on.

**Comment by wizzy25** [comment]
@hisabimbola I tried running the ```publish-docs``` script but I get this error: 
```line 3: pushd: _book: No such file or directory```
The error apparently comes from here: https://github.com/commercetools/nodejs/blob/master/scripts/publish-docs#L3
Would really be nice if @emmenko could shine some light

**Comment by Siilwyn** [comment]
`docs:prepare` and `docs:build` are needed before running that script afaik.

**Comment by emmenko** [comment]
There is a `docs:publish` task. That's the one you want to run ;)

**Comment by Siilwyn** [comment]
That's not what we're after though, this should be automated imho.

**Comment by emmenko** [comment]
Unfortunately github pages has a limit on the number of times you can redeploy. 
But we can give it a try (I would execute the task [here](https://github.com/commercetools/nodejs/blob/master/.travis/after_success.sh#L26))

**Comment by Siilwyn** [comment]
Oh interesting, so it's 10 redeploy limit per hour, should be enough if we only do this on changes to master.

**Comment by hisabimbola** [comment]
Added this to the deployment pipeline, if there is any rate limiting issue we revert to old or find a better solution..

**Comment by hisabimbola** [comment]
After merging this, I notice that there was no deployment on travis and this is because we are using the SSH git url, and that will require us to setup SSH on travis (a whole lot of stuff in there to get that to work). So what I did was use http and github access token already on travis to push to the repo.

Commit regarding that here 705dab12818eb90922db8200fee6f3f7122181da

I hope it works now :crossed_fingers:
