### ISSUE TITLE
Product exporter wrongly throws No products error

### ISSUE THREAD

**Issue by junajan** [commercetools/nodejs#890]
### Support reference number
SUPPORT-4146

### Description
When exporting products using `product-exporter` we use a `process()` function from `sdk-client` which loads products in pages (by default 20 products per page). For every page, it calls processing function and if the count of loaded products is smaller then the page size, [it ends loading](https://github.com/commercetools/nodejs/blob/master/packages/sdk-client/src/client.js#L142).

But if the total amount of products is divisible by `pageSize` (eg 100 products when loading 20 products per page) we load 5 times 20 products and then do another request which returns no products so [we call processing `fn` function](https://github.com/commercetools/nodejs/blob/master/packages/sdk-client/src/client.js#L129) from exporter with an empty array and [it thinks](https://github.com/commercetools/nodejs/blob/master/packages/product-exporter/src/main.js#L105) that there are no products (even if it loaded 100 products in previous calls).

### Expected Behavior
I would stay consistent with other tools - for example `bluebird` or a simple `forEach` or `map` functions do not call processing functions when given an empty array.

So in `sdk-client` I would add a condition which does not call `fn` when there were loaded no products.
And in `product-exporter` I would change how we throw error when there were exported no products.

### Current Behavior

Because the last page has still the same amount of products as `pageSize`, we do one more request which returns an empty array to processing `fn` function which thinks that there are no products so it throws "No products found" error.

**Comment by daern91** [comment]
Above solution sounds good to me. Another one would possibly be to add a variable like `let hasFirstPageBeenProcessed = false` which we then set to `true` in the first iteration if the results are not empty. I think this way we wouldn't have to refactor `product-exporter`. I dont have a strong opinion on it though so WDYT @junajan?
