### ISSUE TITLE
[sdk-middleware-auth] Add support for token

### ISSUE THREAD

**Issue by hisabimbola** [commercetools/nodejs#95]
### Description

In the sphere-node-sdk, it was possible to pass in the token to the client object and it will skip generating another token for the request.
This feature is currently missing in the _sdk-middleware-auth_ middleware.
```coffee
// sphere-node-sdk
client = new SphereClient
  config:
    project_key: projectKey
  access_token: token['access_token'] // not possible with new SDK
```

### Expected Behavior

It should accept the token parameter and if present, use it to authenticate subsequent request.
### Current Behavior
Does not accept valid token.

**Comment by emmenko** [comment]
This is not an issue. If you already have a token then you can simply pass it as `header` in the request object. You don't even need the auth middleware then.

```js
const request = {
  uri: '/foo/bar',
  method: 'GET',
  headers: {
    Authorization: `Bearer ${myAuthToken}`,
  },
}

client.execute(request)
```
