### ISSUE TITLE
No prefix for Lenum attributes (name same as keywords) while exporting

### ISSUE THREAD

**Issue by VasumathiJayakumar** [commercetools/nodejs#970]
### Support reference number

SUPPORT-4036

### Description

The attributes which has the same name as the keywords such "productType" are exported with a prefix "attribute". If there exists an attribute "productType" then it is exported as attribute.productType. If this attribute is an lenum we have an additional column in export file such as "productType.en" without prefix.

### Expected Behavior

The attribute with the language should also have the prefix.

### Current Behavior

No prefix on the exported file

### Context

The customer receives an error, if the exported file is imported because of the prefix missing for the attribute.

<img width="292" alt="enumattribute" src="https://user-images.githubusercontent.com/4718808/48405752-2f6fbb00-e733-11e8-8463-c6120c2827e1.png">

**Comment by junajan** [comment]
When exporting this product:
```json
{
  "id": "a8ca7cba-cfd7-404e-b52b-2150cfa103e3",
  "version": 1,
  "productType": {
    "typeId": "product-type",
    "id": "cad588a6-2c19-4e05-853e-d759ab35e3a3"
  },
  "name": {
    "en": "aaa"
  },
  "description": {
    "en": "aaa"
  },
  "categories": [],
  "categoryOrderHints": {},
  "slug": {
    "en": "aaa"
  },
  "masterVariant": {
    "id": 1,
    "sku": "abcd",
    "key": "abcd",
    "prices": [],
    "images": [],
    "attributes": [
      {
        "name": "productType",
        "value": {
          "label": {
            "de": "AA labele",
            "en": "AA label"
          },
          "key": "aa"
        }
      },
      {
        "name": "description",
        "value": {
          "de": "Abcd description de",
          "en": "Abcd description en"
        }
      }
    ],
    "assets": []
  },
  "variants": [],
  "searchKeywords": {},
  "hasStagedChanges": false,
  "published": false,
  "key": "aaa-test",
  "createdAt": "2018-11-13T09:43:13.304Z",
  "lastModifiedAt": "2018-11-13T09:43:13.304Z"
}
```
I get this CSV:
```csv
"id","productType","name.en","description.en","categories","slug.en","_hasStagedChanges","_published","key","createdAt","lastModifiedAt","variantId","sku","variantKey","images","prices","attribute.productType","productType.de","productType.en","description.de"
"a8ca7cba-cfd7-404e-b52b-2150cfa103e3","test-attr","aaa","Abcd description en","","aaa","false","false","aaa-test","2018-11-13T09:43:13.304Z","2018-11-13T09:43:13.304Z",1,"abcd","abcd","","","aa","AA labele","AA label","Abcd description de"
```

Which has still incorrectly handled conflicting attributes

**Comment by junajan** [comment]
Hello all .. This issue is still occurring when exporting a product with missing description and an attribute named as `description`. The final export should have a column `attribute.description` but it is being exported only as `description`
