### ISSUE TITLE
[sdk-middleware-http] Include headers in request response

### ISSUE THREAD

**Issue by hisabimbola** [commercetools/nodejs#98]
### Description

The headers object is missing from the response.

### Expected Behavior

Should include the headers in the response
### Current Behavior

the response header is striped out.

**Comment by emmenko** [comment]
Can you explain what do you mean exactly?

**Comment by hisabimbola** [comment]
The response headers like the one made available [here](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/client.coffee#L142)

**Comment by emmenko** [comment]
At the moment, they are appended only for errors.
https://github.com/commercetools/nodejs/blob/master/packages/sdk-middleware-http/src/http.js#L73

I guess you can add it for the normal response as well, but then you have to adjust the sdk resolver as well
https://github.com/commercetools/nodejs/blob/master/packages/sdk-client/src/client.js#L44-L45
